### ISSUE TITLE
Running coinflip on k3s fails

### ISSUE THREAD

**Issue by gaussianblurs** [argoproj/argo#1253]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**What happened**:
Running the coinflip example on k3s caused a panic of the workflow-controller

**What you expected to happen**:
It works

**How to reproduce it (as minimally and precisely as possible)**:
`argo submit --kubeconfig "/etc/rancher/k3s/k3s.yaml" --watch https://raw.githubusercontent.com/argoproj/argo/master/examples/coinflip.yaml`

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
argo: v2.2.1
  BuildDate: 2018-10-11T16:26:28Z
  GitCommit: 3b52b26190163d1f72f3aef1a39f9f291378dafb
  GitTreeState: clean
  GitTag: v2.2.1
  GoVersion: go1.10.3
  Compiler: gc
  Platform: linux/amd64
```
- Kubernetes version :
```
k3s version dev (HEAD)
```

**Other debugging information (if applicable)**:
- workflow result:
```
Name:                coinflip-jhb22
Namespace:           default
ServiceAccount:      default
Status:              Error
Message:             node coinflip-jhb22[1].heads uninitialized
Created:             Mon Mar 11 10:36:30 +0100 (6 seconds ago)
Started:             Mon Mar 11 10:36:30 +0100 (6 seconds ago)
Finished:            Mon Mar 11 10:36:36 +0100 (now)
Duration:            6 seconds

STEP               PODNAME                  DURATION  MESSAGE
 ● coinflip-jhb22                                     
 ├---✔ flip-coin   coinflip-jhb22-72744569  5s
```
```
$ kubectl logs <failedpodname> -c init
time="2019-03-11T09:36:32Z" level=info msg="Creating a docker executor"
time="2019-03-11T09:36:32Z" level=info msg="Executor (version: v2.2.1, build_date: 2018-10-11T16:27:29Z) initialized with template:\narchiveLocation: {}\ninputs: {}\nmetadata: {}\nname: flip-coin\noutputs: {}\nscript:\n  command:\n  - python\n  image: python:alpine3.6\n  name: \"\"\n  resources: {}\n  source: |\n    import random\n    result = \"heads\" if random.randint(0,1) == 0 else \"tails\"\n    print(result)\n"
time="2019-03-11T09:36:32Z" level=info msg="Loading script source to /argo/staging/script"
time="2019-03-11T09:36:32Z" level=info msg="Start loading input artifacts..."
time="2019-03-11T09:36:32Z" level=info msg="Alloc=2997 TotalAlloc=9325 Sys=8774 NumGC=3 Goroutines=3"
```
```
$ kubectl logs <failedpodname> -c wait
time="2019-03-11T09:36:34Z" level=info msg="Creating a docker executor"
time="2019-03-11T09:36:34Z" level=info msg="Executor (version: v2.2.1, build_date: 2018-10-11T16:27:29Z) initialized with template:\narchiveLocation: {}\ninputs: {}\nmetadata: {}\nname: flip-coin\noutputs: {}\nscript:\n  command:\n  - python\n  image: python:alpine3.6\n  name: \"\"\n  resources: {}\n  source: |\n    import random\n    result = \"heads\" if random.randint(0,1) == 0 else \"tails\"\n    print(result)\n"
time="2019-03-11T09:36:34Z" level=info msg="Waiting on main container"
time="2019-03-11T09:36:35Z" level=info msg="main container started with container ID: a32fa0a10f692eabe33cc34f5f5dd84032d02161a42077f08397e8ce080b579b"
time="2019-03-11T09:36:35Z" level=info msg="Starting annotations monitor"
time="2019-03-11T09:36:35Z" level=info msg="Starting deadline monitor"
time="2019-03-11T09:36:35Z" level=info msg="docker wait a32fa0a10f692eabe33cc34f5f5dd84032d02161a42077f08397e8ce080b579b"
time="2019-03-11T09:36:35Z" level=error msg="`docker wait a32fa0a10f692eabe33cc34f5f5dd84032d02161a42077f08397e8ce080b579b` failed: Error response from daemon: No such container: a32fa0a10f692eabe33cc34f5f5dd84032d02161a42077f08397e8ce080b579b\n"
time="2019-03-11T09:36:35Z" level=info msg="Main container completed"
time="2019-03-11T09:36:35Z" level=info msg="No sidecars"
time="2019-03-11T09:36:35Z" level=info msg="No output artifacts"
time="2019-03-11T09:36:35Z" level=info msg="Annotations monitor stopped"
time="2019-03-11T09:36:35Z" level=info msg="No output parameters"
time="2019-03-11T09:36:35Z" level=info msg="Capturing script output"
time="2019-03-11T09:36:35Z" level=info msg="[docker logs a32fa0a10f692eabe33cc34f5f5dd84032d02161a42077f08397e8ce080b579b]"
time="2019-03-11T09:36:35Z" level=info msg="Annotating pod with output"
time="2019-03-11T09:36:35Z" level=info msg="Alloc=3020 TotalAlloc=10829 Sys=10342 NumGC=4 Goroutines=8"

```
- workflow-controller logs:
```
time="2019-03-11T09:02:17Z" level=info msg="Marking workflow completed" namespace=default workflow=coinflip-jn2j9
time="2019-03-11T09:02:17Z" level=error msg="Recovered from panic: node coinflip-jn2j9[1].heads uninitialized\ngoroutine 106 [running]:\nruntime/debug.Stack(0xc4207acae0, 0x1248650, 0x5)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).operate.func1(0xc4207acae0)\n\t/root/go/src/github.com/argoproj/argo/workflow/controller/operator.go:114 +0xb5\npanic(0x1091e60, 0xc4207fcc10)\n\t/usr/local/go/src/runtime/panic.go:502 +0x229\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).markNodePhase(0xc4207acae0, 0xc4209153e0, 0x17, 0x1248650, 0x5, 0xc420825b68, 0x1, 0x1, 0x0)\n\t/root/go/src/github.com/argoproj/argo/workflow/controller/operator.go:1070 +0x8e5\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).markNodeError(0xc4207acae0, 0xc4209153e0, 0x17, 0x1343f60, 0xc4207dab40, 0xc4209153e0)\n\t/root/go/src/github.com/argoproj/argo/workflow/controller/operator.go:1095 +0xaa\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeStepGroup(0xc4207acae0, 0xc42025c000, 0x2, 0x4, 0xc4209151a0, 0x11, 0xc420826828, 0xc42071d4e0)\n\t/root/go/src/github.com/argoproj/argo/workflow/controller/steps.go:178 +0x13fc\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeSteps(0xc4207acae0, 0xc42071d200, 0xe, 0xc42090edc0, 0x0, 0x0, 0x0)\n\t/root/go/src/github.com/argoproj/argo/workflow/controller/steps.go:73 +0xa69\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeTemplate(0xc4207acae0, 0xc42071d270, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42071d200, ...)\n\t/root/go/src/github.com/argoproj/argo/workflow/controller/operator.go:943 +0xcac\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).operate(0xc4207acae0)\n\t/root/go/src/github.com/argoproj/argo/workflow/controller/operator.go:155 +0x36d\ngithub.com/argoproj/argo/workflow/controller.(*WorkflowController).processNextItem(0xc42046af00, 0xc4201f2400)\n\t/root/go/src/github.com/argoproj/argo/workflow/controller/controller.go:235 +0x435\ngithub.com/argoproj/argo/workflow/controller.(*WorkflowController).runWorker(0xc42046af00)\n\t/root/go/src/github.com/argoproj/argo/workflow/controller/controller.go:191 +0x2b\ngithub.com/argoproj/argo/workflow/controller.(*WorkflowController).(github.com/argoproj/argo/workflow/controller.runWorker)-fm()\n\t/root/go/src/github.com/argoproj/argo/workflow/controller/controller.go:156 +0x2a\ngithub.com/argoproj/argo/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc4201c2010)\n\t/root/go/src/github.com/argoproj/argo/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54\ngithub.com/argoproj/argo/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc4201c2010, 0x3b9aca00, 0x0, 0x20001, 0xc4201f00c0)\n\t/root/go/src/github.com/argoproj/argo/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbd\ngithub.com/argoproj/argo/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc4201c2010, 0x3b9aca00, 0xc4201f00c0)\n\t/root/go/src/github.com/argoproj/argo/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d\ncreated by github.com/argoproj/argo/workflow/controller.(*WorkflowController).Run\n\t/root/go/src/github.com/argoproj/argo/workflow/controller/controller.go:156 +0x6a8\n" namespace=default workflow=coinflip-jn2j9
time="2019-03-11T09:02:17Z" level=info msg="Workflow update successful" namespace=default workflow=coinflip-jn2j9
time="2019-03-11T09:02:18Z" level=info msg="Labeled pod default/coinflip-jn2j9-2528848564 completed"
time="2019-03-11T09:03:06Z" level=info msg="Alloc=3866 TotalAlloc=59400 Sys=13514 NumGC=58 Goroutines=73"
time="2019-03-11T09:08:06Z" level=info msg="Alloc=3863 TotalAlloc=59451 Sys=13514 NumGC=60 Goroutines=73"
time="2019-03-11T09:13:06Z" level=info msg="Alloc=3812 TotalAlloc=59484 Sys=13514 NumGC=63 Goroutines=73"
time="2019-03-11T09:18:06Z" level=info msg="Alloc=3830 TotalAlloc=59742 Sys=13514 NumGC=65 Goroutines=73"
time="2019-03-11T09:23:06Z" level=info msg="Alloc=3813 TotalAlloc=59792 Sys=13514 NumGC=68 Goroutines=73"
time="2019-03-11T09:28:06Z" level=info msg="Alloc=3813 TotalAlloc=59827 Sys=13514 NumGC=70 Goroutines=73"
```

**Comment by gaussianblurs** [comment]
Also, the Argo UI reports the workflow as still running

**Comment by sarabala1979** [comment]
not reproduced in v2.3.

**Comment by tedostrem** [comment]
I'm having this issue on v2.4.2 on k3s.
```
ted@carbon~/.../argo(master)$ k logs -f coinflip-8r4b7-4122689470 wait
time="2019-11-30T07:14:33Z" level=info msg="Creating a docker executor"
time="2019-11-30T07:14:33Z" level=info msg="Executor (version: v2.4.2, build_date: 2019-10-21T18:39:09Z) initialized (pod: default/coinflip-8r4b7-4122689470) with template:\n{\"name\":\"flip-coin\",\"arguments\":{},\"inputs\":{},\"outputs\":{},\"metadata\":{},\"script\":{\"name\":\"\",\"image\":\"python:alpine3.6\",\"command\":[\"python\"],\"resources\":{},\"source\":\"import random\\nresult = \\\"heads\\\" if random.randint(0,1) == 0 else \\\"tails\\\"\\nprint(result)\\n\"}}"
time="2019-11-30T07:14:33Z" level=info msg="Waiting on main container"
time="2019-11-30T07:14:33Z" level=info msg="main container started with container ID: 3deec79debce444163626adb1d5c5f77ff0200e2f0c499e61aff8d2f326f5214"
time="2019-11-30T07:14:33Z" level=info msg="Starting annotations monitor"
time="2019-11-30T07:14:33Z" level=info msg="Execution control set from API: {<nil> true}"
time="2019-11-30T07:14:33Z" level=info msg="docker wait 3deec79debce444163626adb1d5c5f77ff0200e2f0c499e61aff8d2f326f5214"
time="2019-11-30T07:14:33Z" level=info msg="Starting deadline monitor"
time="2019-11-30T07:14:33Z" level=error msg="`docker wait 3deec79debce444163626adb1d5c5f77ff0200e2f0c499e61aff8d2f326f5214` failed: Error response from daemon: No such container: 3deec79debce444163626adb1d5c5f77ff0200e2f0c499e61aff8d2f326f5214\n"
time="2019-11-30T07:14:33Z" level=warning msg="Failed to wait for container id '3deec79debce444163626adb1d5c5f77ff0200e2f0c499e61aff8d2f326f5214': Error response from daemon: No such container: 3deec79debce444163626adb1d5c5f77ff0200e2f0c499e61aff8d2f326f5214"
time="2019-11-30T07:14:33Z" level=error msg="executor error: Error response from daemon: No such container: 3deec79debce444163626adb1d5c5f77ff0200e2f0c499e61aff8d2f326f5214\ngithub.com/argoproj/argo/errors.New\n\t/go/src/github.com/argoproj/argo/errors/errors.go:49\ngithub.com/argoproj/argo/errors.InternalError\n\t/go/src/github.com/argoproj/argo/errors/errors.go:60\ngithub.com/argoproj/argo/workflow/common.RunCommand\n\t/go/src/github.com/argoproj/argo/workflow/common/util.go:406\ngithub.com/argoproj/argo/workflow/executor/docker.(*DockerExecutor).Wait\n\t/go/src/github.com/argoproj/argo/workflow/executor/docker/docker.go:95\ngithub.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).Wait.func1\n\t/go/src/github.com/argoproj/argo/workflow/executor/executor.go:892\nk8s.io/apimachinery/pkg/util/wait.ExponentialBackoff\n\t/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:265\ngithub.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).Wait\n\t/go/src/github.com/argoproj/argo/workflow/executor/executor.go:891\ngithub.com/argoproj/argo/cmd/argoexec/commands.waitContainer\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/commands/wait.go:40\ngithub.com/argoproj/argo/cmd/argoexec/commands.NewWaitCommand.func1\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/commands/wait.go:16\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/src/github.com/spf13/cobra/command.go:766\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/src/github.com/spf13/cobra/command.go:852\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/src/github.com/spf13/cobra/command.go:800\nmain.main\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/main.go:17\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:201\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1333"
time="2019-11-30T07:14:33Z" level=info msg="No output parameters"
time="2019-11-30T07:14:33Z" level=info msg="No output artifacts"
time="2019-11-30T07:14:33Z" level=info msg="Capturing script output"
time="2019-11-30T07:14:33Z" level=info msg="[docker logs 3deec79debce444163626adb1d5c5f77ff0200e2f0c499e61aff8d2f326f5214]"
time="2019-11-30T07:14:33Z" level=info msg="Annotations monitor stopped"
time="2019-11-30T07:14:33Z" level=info msg="Annotating pod with output"
time="2019-11-30T07:14:33Z" level=info msg="Killing sidecars"
time="2019-11-30T07:14:33Z" level=info msg="Alloc=5153 TotalAlloc=11572 Sys=70590 NumGC=4 Goroutines=12"
```

**Comment by sarabala1979** [comment]
configure PNS executor in workflow-controller-configmap and try

**Comment by nmandery** [comment]
@tedostrem: I had the same issue with v2.4.2 on k3s, but switching from the default `docker` executor to the `k8sapi` executor resolved the issue for me:

k8sapi-executor.yml:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  config: |
    containerRuntimeExecutor: k8sapi
```

```
kubectl apply -n argo -f k8sapi-executor.yml
```

**Comment by flxs** [comment]
I'm having the same issue on k3s v1.0.0 (which is Kubernetes v1.6), argo v2.4.2.

I've had to edit install.yml from Master since the `Deployment` kind is now part of `apps/v1` in Kubernetes 1.6; afterwards, I was able to apply the yaml without errors.

I've next applied the fix by @nmandery, but it doesn't work for me, the k8sapi executor still seems to require Docker somehow (I'm using the k3s default containerd). I'm getting the same errors as before. I can see in the workflow controller's logs that the change has been detected, but it doesn't have any observable effect.

Using the `kubelet` executor instead gets me a step further, but then I'm running into the issue described in #1021. Giving the default service account the admin clusterrole works, even though it's ugly (but it's only a throwaway dev cluster so whatever.)

The `kubelet` executor then proceeds to query the k8s api on my primary IP address (it's bound to 127.0.0.1 via `k3sup`, it's a single-node dev cluster and I'd like to use an SSH tunnel to reach the k8s API).

I've made the k8s API reachable on the public interface from pod IPs via iptables rules, just to see what happens, now I'm getting weird 403 Forbidden errors:

```
failed to save outputs: unexpected non 200 status code: 403, body: Forbidden (user=system:serviceaccount:argo:default, verb=get, resource=nodes, subresource=proxy)
```

I didn't dig any deeper here because this is already very far from an decent configuration. No idea what's broken there, but it appears to be thoroughly broken.

My k3s is pretty standard; I've used k3sup to set it up on an Ubuntu 18.04 VM like this:

```
k3sup install --ip 127.0.0.1 --user ubuntu --k3s-extra-args '--no-deploy traefik'
```

Installing argo as described above is pretty much everything noteworthy that I've done to that cluster.

**Comment by nmandery** [comment]
@flxs For what its is worth: I am using the `pns` executor now as I experienced some other issues with the `k8sapi` executor with dag workflows.

**Comment by flxs** [comment]
Weird, it seems argo silently reverts to the default Docker executor when I set the executor to `pns`, at least I'm getting the same errors I got with the default config. The behaviour is the same if I put in a random string as the executor, and for `k8sapi`. Do I need to install those executors separately?

I'm setting it like this:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  config: |
    containerRuntimeExecutor: pns
```

The workflow controller pod seems to have discovered the change:

```
time="2019-12-18T13:27:56Z" level=info msg="Detected ConfigMap update. Updating the controller config."
time="2019-12-18T13:27:56Z" level=info msg="workflow controller configuration from workflow-controller-configmap:\ncontainerRuntimeExecutor: pns\n"
```

Yet workflow pods still try (and fail) to mount the Docker socket.
