### ISSUE TITLE
bash completion improvements

### ISSUE THREAD

**Issue by edwinpjacques** [argoproj/argo#1436]
**Is this a BUG REPORT or FEATURE REQUEST?**: 

FEATURE REQUEST

**What happened**:

There are a number of issues with bash completion that can be fixed pretty easily:

#### "log" command completes with workflows rather than pods

```
Edwins-MacBook-Pro:argo-cd edwin$ argo logs 
artifact-passing-br72f  coinflip-5ktdk          coinflip-m587w          coinflip-s9xdk          steps-sp22h             
artifact-passing-mldqq  coinflip-jg4g6          coinflip-qvqbl          conditional-ntp9c       
artifact-passing-zg55d  coinflip-jmvx7          coinflip-rd6v4          steps-ptdtq             
Edwins-MacBook-Pro:argo-cd edwin$ argo logs artifact-passing-br72f
FATA[0000] pods "artifact-passing-br72f" not found      
```

Should be enhanced to complete with pods, and if (-w|--workflow) is supplied, complete with workflows as it does now.

#### "submit" should filter out only yaml/yml or json files from completion list

```
Edwins-MacBook-Pro:argo-cd edwin$ argo submit 
.argo-ci/                .golangci.yml            Makefile                 common/                  manifests/               ui/
.circleci/               CHANGELOG.md             OWNERS                   controller/              mkdocs.yml               util/
.codecov.yml             Dockerfile               Procfile                 dist/                    pkg/                     vendor/
.dockerignore            Dockerfile.dev           README.md                docs/                    reposerver/              
.git/                    Gopkg.lock               VERSION                  errors/                  resource_customizations/ 
.github/                 Gopkg.toml               assets/                  examples/                server/                  
.gitignore               LICENSE                  cmd/                     hack/                    test/                    
```

#### "list --status=' '" produces a segmentation fault

```
ejacques-mbp:examples ejacques$ argo list --status=" "
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1c55173]

goroutine 1 [running]:
github.com/argoproj/argo/cmd/argo/commands.NewListCommand.func1(0xc00024e000, 0xc000227a30, 0x0, 0x1)
	/Users/ejacques/go/src/github.com/argoproj/argo/cmd/argo/commands/list.go:54 +0xe03
github.com/argoproj/argo/vendor/github.com/spf13/cobra.(*Command).execute(0xc00024e000, 0xc000227a10, 0x1, 0x1, 0xc00024e000, 0xc000227a10)
	/Users/ejacques/go/src/github.com/argoproj/argo/vendor/github.com/spf13/cobra/command.go:766 +0x2ae
github.com/argoproj/argo/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0001f7180, 0x0, 0xc000187f88, 0x100554f)
	/Users/ejacques/go/src/github.com/argoproj/argo/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
github.com/argoproj/argo/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/Users/ejacques/go/src/github.com/argoproj/argo/vendor/github.com/spf13/cobra/command.go:800
main.main()
	/Users/ejacques/go/src/github.com/argoproj/argo/cmd/argo/main.go:17 +0x2c
```

#### "suspend/terminate/wait/watch/resume/retry" commands should only complete workflows in the appropriate state

All of those commands return the result of "argo list".

**What you expected to happen**:

#### Complete "logs" command with either pods or workflows as appropriate

```
Edwins-MacBook-Pro:argo edwin$ argo logs 
artifact-passing-br72f-4272859315  coinflip-5ktdk-666293366           coinflip-qvqbl-630379513           steps-ptdtq-1129304726
artifact-passing-br72f-570194761   coinflip-jg4g6-2175945733          coinflip-rd6v4-1951658687          steps-ptdtq-126479429
artifact-passing-mldqq-3331757295  coinflip-jmvx7-2288525212          coinflip-rd6v4-2832038430          steps-sp22h-1028943132
artifact-passing-zg55d-1757963829  coinflip-jmvx7-830609345           coinflip-s9xdk-1282470043          steps-sp22h-1079275989
artifact-passing-zg55d-3501659643  coinflip-m587w-2484450197          coinflip-s9xdk-3902802574          steps-sp22h-3280091627
coinflip-5ktdk-3334567571          coinflip-qvqbl-1757769684          steps-ptdtq-1112527107             
Edwins-MacBook-Pro:argo edwin$ argo logs coinflip-qvqbl-1757769684
it was heads
Edwins-MacBook-Pro:argo edwin$ argo logs --workflow 
artifact-passing-br72f  coinflip-5ktdk          coinflip-m587w          coinflip-s9xdk          steps-sp22h             
artifact-passing-mldqq  coinflip-jg4g6          coinflip-qvqbl          conditional-ntp9c       
artifact-passing-zg55d  coinflip-jmvx7          coinflip-rd6v4          steps-ptdtq             
Edwins-MacBook-Pro:argo edwin$ argo logs --workflow coinflip-qvqbl
flip-coin:      heads
heads:  it was heads
```

#### "submit" command completes only yaml/yml or json files

```
Edwins-MacBook-Pro:argo edwin$ argo submit 
.argo-ci           assets             docs               gometalinter.json  pkg                vendor             
.git               cmd                errors             hack               test               workflow           
.github            community          examples           hooks              ui                 
api                dist               golangci.yml       manifests          util               
```

#### "retry" should only return failed workflows

**How to reproduce it (as minimally and precisely as possible)**:

See above.

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
$ argo version
argo: v2.3.0
  BuildDate: 2019-05-20T22:11:23Z
  GitCommit: 88fcc70dcf6e60697e6716edc7464a403c49b27e
  GitTreeState: clean
  GitTag: v2.3.0
  GoVersion: go1.11.5
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2019-06-07T09:55:27Z"
  compiler: gc
  gitCommit: 5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0
  gitTreeState: clean
  gitVersion: v1.14.3
  goVersion: go1.12.5
  major: "1"
  minor: "14"
  platform: darwin/amd64
serverVersion:
  buildDate: "2019-06-06T01:36:19Z"
  compiler: gc
  gitCommit: 5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0
  gitTreeState: clean
  gitVersion: v1.14.3
  goVersion: go1.12.5
  major: "1"
  minor: "14"
  platform: linux/amd64
```

**Comment by edwinpjacques** [comment]
Resolved by #1437
