### ISSUE TITLE
argo list --status crashing when there is a space in the status

### ISSUE THREAD

**Issue by edwinpjacques** [argoproj/argo#1440]
**Is this a BUG REPORT or FEATURE REQUEST?**:

BUG REPORT

**What happened**:

argo CLI SIGSEGV when --status=" " (any space in the status argument)

```
ejacques-mbp:argo ejacques$ argo list --status=' '
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1bd2a8f]

goroutine 1 [running]:
github.com/argoproj/argo/cmd/argo/commands.NewListCommand.func1(0xc0001ac500, 0xc000235580, 0x0, 0x1)
	/go/src/github.com/argoproj/argo/cmd/argo/commands/list.go:53 +0xc1f
github.com/spf13/cobra.(*Command).execute(0xc0001ac500, 0xc000235560, 0x1, 0x1, 0xc0001ac500, 0xc000235560)
	/go/src/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0xc000195680, 0xc0001aca00, 0xc0001ac780, 0xc0001ac500)
	/go/src/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0xc000195680, 0x0, 0xc000038ea0)
	/go/src/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/go/src/github.com/argoproj/argo/cmd/argo/main.go:17 +0x27
```

**What you expected to happen**:

```
ejacques-mbp:argo ejacques$ argo list --status=' '
NAME                     STATUS                AGE   DURATION   PRIORITY
artifact-passing-42zlm   Running (Suspended)   1m    1m         0
artifact-passing-44qcn   Succeeded             34m   5m         0
artifact-passing-9b9nm   Succeeded             33m   10s        0
artifact-passing-6b4hf   Succeeded             33m   11s        0
artifact-passing-57mpj   Succeeded             33m   11s        0
artifact-passing-6bkj7   Succeeded             35m   23s        0
artifact-passing-b8s6q   Succeeded             36m   11s        0
artifact-passing-9n6dp   Succeeded             37m   15s        0
artifact-passing-2dw47   Succeeded             1h    55s        0
artifact-passing-dbsb7   Succeeded             1h    10s        0
artifact-passing-zz549   Succeeded             1h    11s        0
resubmit-znlpk           Error                 4h    0s         0
artifact-passing-2nrvn   Succeeded             4h    1m         0
artifact-passing-mr9vg   Succeeded             4h    11s        0
artifact-passing-gtz8d   Succeeded             4h    10s        0
artifact-passing-dvzsl   Succeeded             4h    10s        0
```

**How to reproduce it (as minimally and precisely as possible)**:

See above.

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
$ argo version
argo: v2.3.0
  BuildDate: 2019-05-20T22:11:23Z
  GitCommit: 88fcc70dcf6e60697e6716edc7464a403c49b27e
  GitTreeState: clean
  GitTag: v2.3.0
  GoVersion: go1.11.5
  Compiler: gc
  Platform: darwin/amd64```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2019-06-07T09:55:27Z"
  compiler: gc
  gitCommit: 5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0
  gitTreeState: clean
  gitVersion: v1.14.3
  goVersion: go1.12.5
  major: "1"
  minor: "14"
  platform: darwin/amd64
serverVersion:
  buildDate: "2019-04-08T17:02:58Z"
  compiler: gc
  gitCommit: b7394102d6ef778017f2ca4046abbaa23b88c290
  gitTreeState: clean
  gitVersion: v1.14.1
  goVersion: go1.12.1
  major: "1"
  minor: "14"
  platform: linux/amd64
```

**Comment by edwinpjacques** [comment]
Resolved by #1437
