### ISSUE TITLE
[Bug] argo lint fails when workflow argument does not have value

### ISSUE THREAD

**Issue by Ark-kun** [argoproj/argo#1619]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**What happened**:
argo lint fails when workflow argument does not have value

**What you expected to happen**:
Based on the comments in Argo code, I expect argo lint not to fail in this case.
>// if we are just linting we don't care if spec.arguments.parameters.XXX doesn't have an
>// explicit value. workflows without a default value is a desired use case

https://github.com/argoproj/argo/blob/e96a09a3911f039038ea3038bed3a8cd8d63e269/workflow/common/validate.go#L50..L52

**How to reproduce it (as minimally and precisely as possible)**:

```shell
echo '
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: whalesay
  arguments:
    parameters:
    - name: a
  templates:
  - name: whalesay
    inputs:
      parameters:
      - name: a
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{workflow.parameters.a}}"]
' | argo lint /dev/stdin
```
>FATA[0000] /dev/stdin: templates.whalesay inputs.parameters.a was not supplied

**Environment**:
- Argo version:
```
$ argo version
argo: v2.3.0
  BuildDate: 2019-05-20T22:11:09Z
  GitCommit: 88fcc70dcf6e60697e6716edc7464a403c49b27e
  GitTreeState: clean
  GitTag: v2.3.0
  GoVersion: go1.11.5
  Compiler: gc
  Platform: linux/amd64
```

The error is raised inside [ProcessArgs](https://github.com/argoproj/argo/blob/aa3a8f1c99fcb70bb199750644f74b17812cc586/workflow/common/util.go#L266)

P.S. On v2.4.0rc1 this just crashes:
```
argo: v2.4.0-rc1
  BuildDate: 2019-08-08T22:59:15Z
  GitCommit: 6131721f43545196399d7ffe3a72c1b9dc04df87
  GitTreeState: clean
  GitTag: v2.4.0-rc1
  GoVersion: go1.11.5
  Compiler: gc
  Platform: linux/amd64
```
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xf60bb5]

goroutine 1 [running]:
github.com/argoproj/argo/pkg/client/clientset/versioned.(*Clientset).ArgoprojV1alpha1(0x0, 0xc00073e0c0, 0x14efbfb)
	/go/src/github.com/argoproj/argo/pkg/client/clientset/versioned/clientset.go:26 +0x5
github.com/argoproj/argo/workflow/validate.ValidateWorkflow(0x16779a0, 0x0, 0x14e9be8, 0x7, 0xc000735880, 0x1, 0x0, 0x0, 0x0, 0x199)
	/go/src/github.com/argoproj/argo/workflow/validate/validate.go:90 +0x27e
github.com/argoproj/argo/workflow/validate.LintWorkflowFile(0x16779a0, 0x0, 0x14e9be8, 0x7, 0x7ffd43f380e6, 0xa, 0x1, 0x1, 0x11)
	/go/src/github.com/argoproj/argo/workflow/validate/lint.go:65 +0x4cc
github.com/argoproj/argo/cmd/argo/commands.NewLintCommand.func1(0xc0000ef680, 0xc0002528f0, 0x1, 0x1)
	/go/src/github.com/argoproj/argo/cmd/argo/commands/lint.go:50 +0x283
github.com/spf13/cobra.(*Command).execute(0xc0000ef680, 0xc0002528a0, 0x1, 0x1, 0xc0000ef680, 0xc0002528a0)
	/go/src/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000eea00, 0xc000116280, 0xc000116000, 0xc0000efb80)
	/go/src/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0xc0000eea00, 0x0, 0xc00014ae40)
	/go/src/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/go/src/github.com/argoproj/argo/cmd/argo/main.go:17 +0x27

```

**Comment by NikeNano** [comment]
Is there any intention to fix this or is this the expected behaviour?
