### ISSUE TITLE
failed to save outputs: invalid configuration: no configuration has been provided

### ISSUE THREAD

**Issue by rmgpinto** [argoproj/argo#1928]
**What happened**:
When I run `argo submit --namespace argo --serviceaccount argo --watch https://raw.githubusercontent.com/argoproj/argo/master/examples/hello-world.yaml`
I get the error:
```
STEP                             PODNAME            DURATION  MESSAGE
 ⚠ hello-world-jjkd4 (whalesay)   hello-world-42xlv  2s        failed to save outputs: invalid configuration: no configuration has been provided
```

**What you expected to happen**:
The `hello-world` to run successfully.

**How to reproduce it (as minimally and precisely as possible)**:
I've installed `argo` with: 
```
kubectl create namespace argo
kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo/v2.4.3/manifests/namespace-install.yaml
```

**Anything else we need to know?**:
N/A

**Environment**:
- Argo version: 
```
$ argo version
argo: v2.4.2
  BuildDate: 2019-10-21T18:39:52Z
  GitCommit: 675c66267f0c916de0f233d8101aa0646acb46d4
  GitTreeState: clean
  GitTag: v2.4.2
  GoVersion: go1.11.5
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2019-06-19T16:40:16Z"
  compiler: gc
  gitCommit: e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529
  gitTreeState: clean
  gitVersion: v1.15.0
  goVersion: go1.12.5
  major: "1"
  minor: "15"
  platform: darwin/amd64
serverVersion:
  buildDate: "2019-12-22T23:14:11Z"
  compiler: gc
  gitCommit: c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2
  gitTreeState: clean
  gitVersion: v1.14.9-eks-c0eccc
  goVersion: go1.12.12
  major: "1"
  minor: 14+
  platform: linux/amd64
```

****Logs****:
- workflow result:
```
Name:                hello-world-42xlv
Namespace:           argo
ServiceAccount:      argo
Status:              Error
Message:             failed to save outputs: invalid configuration: no configuration has been provided
Created:             Thu Jan 09 11:44:04 +0100 (13 minutes ago)
Started:             Thu Jan 09 11:44:04 +0100 (13 minutes ago)
Finished:            Thu Jan 09 11:44:25 +0100 (13 minutes ago)
Duration:            21 seconds

STEP                             PODNAME            DURATION  MESSAGE
 ⚠ hello-world-42xlv (whalesay)  hello-world-42xlv  20s       failed to save outputs: invalid configuration: no configuration has been provided

```
- executor logs:
```
kubectl logs <failedpodname> -c wait
panic: invalid configuration: no configuration has been provided

goroutine 1 [running]:
github.com/argoproj/argo/cmd/argoexec/commands.checkErr(0x1b3baa0, 0xc000298300)
	/go/src/github.com/argoproj/argo/cmd/argoexec/commands/root.go:110 +0xb6
github.com/argoproj/argo/cmd/argoexec/commands.initExecutor(0xc0002c4aa0)
	/go/src/github.com/argoproj/argo/cmd/argoexec/commands/root.go:70 +0x6f
github.com/argoproj/argo/cmd/argoexec/commands.waitContainer(0x0, 0x0)
	/go/src/github.com/argoproj/argo/cmd/argoexec/commands/wait.go:26 +0x2e
github.com/argoproj/argo/cmd/argoexec/commands.NewWaitCommand.func1(0xc0000e2f00, 0x29379e8, 0x0, 0x0)
	/go/src/github.com/argoproj/argo/cmd/argoexec/commands/wait.go:16 +0x22
github.com/spf13/cobra.(*Command).execute(0xc0000e2f00, 0x29379e8, 0x0, 0x0, 0xc0000e2f00, 0x29379e8)
	/go/src/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000e2500, 0x0, 0x0, 0x0)
	/go/src/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0xc0000e2500, 0x0, 0xc0005bcf00)
	/go/src/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/go/src/github.com/argoproj/argo/cmd/argoexec/main.go:17 +0x27
```
- workflow-controller logs:
```
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
time="2020-01-09T10:42:56Z" level=info msg="workflow controller configuration from workflow-controller-configmap:\n      namespace: argo\n"
time="2020-01-09T10:42:56Z" level=info msg="Persistence configuration disabled"
time="2020-01-09T10:42:56Z" level=info msg="Workflow Controller (version: v2.4.3) starting"
time="2020-01-09T10:42:56Z" level=info msg="Workers: workflow: 8, pod: 8"
time="2020-01-09T10:42:56Z" level=info msg="Watch Workflow controller config map updates"
time="2020-01-09T10:42:56Z" level=info msg="Starting workflow TTL controller (resync 20m0s)"
time="2020-01-09T10:42:56Z" level=info msg="Detected ConfigMap update. Updating the controller config."
time="2020-01-09T10:42:56Z" level=info msg="workflow controller configuration from workflow-controller-configmap:\n      namespace: argo\n"
time="2020-01-09T10:42:56Z" level=info msg="Persistence configuration disabled"
time="2020-01-09T10:42:56Z" level=info msg="Started workflow TTL worker"
time="2020-01-09T10:42:56Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-mbdtl
time="2020-01-09T10:42:56Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=hello-world-mbdtl
time="2020-01-09T10:42:56Z" level=info msg="Pod node hello-world-mbdtl (hello-world-mbdtl) initialized Pending" namespace=argo workflow=hello-world-mbdtl
time="2020-01-09T10:42:56Z" level=info msg="Created pod: hello-world-mbdtl (hello-world-mbdtl)" namespace=argo workflow=hello-world-mbdtl
time="2020-01-09T10:42:56Z" level=info msg="Workflow update successful" namespace=argo workflow=hello-world-mbdtl
time="2020-01-09T10:42:57Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-mbdtl
time="2020-01-09T10:42:57Z" level=info msg="Updating node hello-world-mbdtl (hello-world-mbdtl) message: ContainerCreating"
time="2020-01-09T10:42:57Z" level=info msg="Skipped pod hello-world-mbdtl (hello-world-mbdtl) creation: already exists" namespace=argo workflow=hello-world-mbdtl
time="2020-01-09T10:42:57Z" level=info msg="Workflow update successful" namespace=argo workflow=hello-world-mbdtl
time="2020-01-09T10:42:58Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-mbdtl
time="2020-01-09T10:42:58Z" level=info msg="Skipped pod hello-world-mbdtl (hello-world-mbdtl) creation: already exists" namespace=argo workflow=hello-world-mbdtl
time="2020-01-09T10:43:19Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-mbdtl
time="2020-01-09T10:43:19Z" level=info msg="Updating node hello-world-mbdtl (hello-world-mbdtl) status Pending -> Error"
time="2020-01-09T10:43:19Z" level=info msg="Updating node hello-world-mbdtl (hello-world-mbdtl) message: failed to save outputs: invalid configuration: no configuration has been provided"
time="2020-01-09T10:43:19Z" level=info msg="Updated phase Running -> Error" namespace=argo workflow=hello-world-mbdtl
time="2020-01-09T10:43:19Z" level=info msg="Updated message  -> failed to save outputs: invalid configuration: no configuration has been provided" namespace=argo workflow=hello-world-mbdtl
time="2020-01-09T10:43:19Z" level=info msg="Marking workflow completed" namespace=argo workflow=hello-world-mbdtl
time="2020-01-09T10:43:19Z" level=info msg="Checking daemoned children of " namespace=argo workflow=hello-world-mbdtl
time="2020-01-09T10:43:19Z" level=info msg="Workflow update successful" namespace=argo workflow=hello-world-mbdtl
time="2020-01-09T10:43:20Z" level=info msg="Labeled pod argo/hello-world-mbdtl completed"
time="2020-01-09T10:44:04Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-42xlv
time="2020-01-09T10:44:04Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=hello-world-42xlv
time="2020-01-09T10:44:04Z" level=info msg="Pod node hello-world-42xlv (hello-world-42xlv) initialized Pending" namespace=argo workflow=hello-world-42xlv
time="2020-01-09T10:44:04Z" level=info msg="Created pod: hello-world-42xlv (hello-world-42xlv)" namespace=argo workflow=hello-world-42xlv
time="2020-01-09T10:44:04Z" level=info msg="Workflow update successful" namespace=argo workflow=hello-world-42xlv
time="2020-01-09T10:44:05Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-42xlv
time="2020-01-09T10:44:05Z" level=info msg="Updating node hello-world-42xlv (hello-world-42xlv) message: ContainerCreating"
time="2020-01-09T10:44:05Z" level=info msg="Skipped pod hello-world-42xlv (hello-world-42xlv) creation: already exists" namespace=argo workflow=hello-world-42xlv
time="2020-01-09T10:44:05Z" level=info msg="Workflow update successful" namespace=argo workflow=hello-world-42xlv
time="2020-01-09T10:44:06Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-42xlv
time="2020-01-09T10:44:06Z" level=info msg="Skipped pod hello-world-42xlv (hello-world-42xlv) creation: already exists" namespace=argo workflow=hello-world-42xlv
time="2020-01-09T10:44:11Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-42xlv
time="2020-01-09T10:44:11Z" level=info msg="Updating node hello-world-42xlv (hello-world-42xlv) message: ErrImagePull: rpc error: code = Unknown desc = Error response from daemon: unexpected EOF"
time="2020-01-09T10:44:11Z" level=info msg="Skipped pod hello-world-42xlv (hello-world-42xlv) creation: already exists" namespace=argo workflow=hello-world-42xlv
time="2020-01-09T10:44:11Z" level=info msg="Workflow update successful" namespace=argo workflow=hello-world-42xlv
time="2020-01-09T10:44:12Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-42xlv
time="2020-01-09T10:44:12Z" level=info msg="Skipped pod hello-world-42xlv (hello-world-42xlv) creation: already exists" namespace=argo workflow=hello-world-42xlv
time="2020-01-09T10:44:23Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-42xlv
time="2020-01-09T10:44:23Z" level=info msg="Updating node hello-world-42xlv (hello-world-42xlv) message: ImagePullBackOff: Back-off pulling image \"docker/whalesay:latest\""
time="2020-01-09T10:44:23Z" level=info msg="Skipped pod hello-world-42xlv (hello-world-42xlv) creation: already exists" namespace=argo workflow=hello-world-42xlv
time="2020-01-09T10:44:23Z" level=info msg="Workflow update successful" namespace=argo workflow=hello-world-42xlv
time="2020-01-09T10:44:24Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-42xlv
time="2020-01-09T10:44:24Z" level=info msg="Skipped pod hello-world-42xlv (hello-world-42xlv) creation: already exists" namespace=argo workflow=hello-world-42xlv
time="2020-01-09T10:44:25Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-42xlv
time="2020-01-09T10:44:25Z" level=info msg="Updating node hello-world-42xlv (hello-world-42xlv) status Pending -> Error"
time="2020-01-09T10:44:25Z" level=info msg="Updating node hello-world-42xlv (hello-world-42xlv) message: failed to save outputs: invalid configuration: no configuration has been provided"
time="2020-01-09T10:44:25Z" level=info msg="Updated phase Running -> Error" namespace=argo workflow=hello-world-42xlv
time="2020-01-09T10:44:25Z" level=info msg="Updated message  -> failed to save outputs: invalid configuration: no configuration has been provided" namespace=argo workflow=hello-world-42xlv
time="2020-01-09T10:44:25Z" level=info msg="Marking workflow completed" namespace=argo workflow=hello-world-42xlv
time="2020-01-09T10:44:25Z" level=info msg="Checking daemoned children of " namespace=argo workflow=hello-world-42xlv
time="2020-01-09T10:44:25Z" level=info msg="Workflow update successful" namespace=argo workflow=hello-world-42xlv
time="2020-01-09T10:44:26Z" level=info msg="Labeled pod argo/hello-world-42xlv completed"
time="2020-01-09T10:47:56Z" level=info msg="Alloc=4651 TotalAlloc=20011 Sys=70078 NumGC=8 Goroutines=69"
time="2020-01-09T10:50:35Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-bfj4s
time="2020-01-09T10:50:35Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=hello-world-bfj4s
time="2020-01-09T10:50:35Z" level=info msg="Pod node hello-world-bfj4s (hello-world-bfj4s) initialized Pending" namespace=argo workflow=hello-world-bfj4s
time="2020-01-09T10:50:35Z" level=info msg="Created pod: hello-world-bfj4s (hello-world-bfj4s)" namespace=argo workflow=hello-world-bfj4s
time="2020-01-09T10:50:35Z" level=info msg="Workflow update successful" namespace=argo workflow=hello-world-bfj4s
time="2020-01-09T10:50:36Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-bfj4s
time="2020-01-09T10:50:36Z" level=info msg="Updating node hello-world-bfj4s (hello-world-bfj4s) message: ContainerCreating"
time="2020-01-09T10:50:36Z" level=info msg="Skipped pod hello-world-bfj4s (hello-world-bfj4s) creation: already exists" namespace=argo workflow=hello-world-bfj4s
time="2020-01-09T10:50:36Z" level=info msg="Workflow update successful" namespace=argo workflow=hello-world-bfj4s
time="2020-01-09T10:50:37Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-bfj4s
time="2020-01-09T10:50:37Z" level=info msg="Skipped pod hello-world-bfj4s (hello-world-bfj4s) creation: already exists" namespace=argo workflow=hello-world-bfj4s
time="2020-01-09T10:50:39Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-bfj4s
time="2020-01-09T10:50:39Z" level=info msg="Updating node hello-world-bfj4s (hello-world-bfj4s) status Pending -> Error"
time="2020-01-09T10:50:39Z" level=info msg="Updating node hello-world-bfj4s (hello-world-bfj4s) message: failed to save outputs: invalid configuration: no configuration has been provided"
time="2020-01-09T10:50:39Z" level=info msg="Updated phase Running -> Error" namespace=argo workflow=hello-world-bfj4s
time="2020-01-09T10:50:39Z" level=info msg="Updated message  -> failed to save outputs: invalid configuration: no configuration has been provided" namespace=argo workflow=hello-world-bfj4s
time="2020-01-09T10:50:39Z" level=info msg="Marking workflow completed" namespace=argo workflow=hello-world-bfj4s
time="2020-01-09T10:50:39Z" level=info msg="Checking daemoned children of " namespace=argo workflow=hello-world-bfj4s
time="2020-01-09T10:50:39Z" level=info msg="Workflow update successful" namespace=argo workflow=hello-world-bfj4s
time="2020-01-09T10:50:40Z" level=info msg="Labeled pod argo/hello-world-bfj4s completed"
W0109 10:52:31.297306       1 reflector.go:289] github.com/argoproj/argo/workflow/controller/config_controller.go:116: watch of *v1.ConfigMap ended with: too old resource version: 691299 (692339)
time="2020-01-09T10:52:56Z" level=info msg="Alloc=4777 TotalAlloc=20986 Sys=70078 NumGC=10 Goroutines=69"
time="2020-01-09T10:53:38Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-jjkd4
time="2020-01-09T10:53:38Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=hello-world-jjkd4
time="2020-01-09T10:53:38Z" level=info msg="Pod node hello-world-jjkd4 (hello-world-jjkd4) initialized Pending" namespace=argo workflow=hello-world-jjkd4
time="2020-01-09T10:53:38Z" level=info msg="Created pod: hello-world-jjkd4 (hello-world-jjkd4)" namespace=argo workflow=hello-world-jjkd4
time="2020-01-09T10:53:38Z" level=info msg="Workflow update successful" namespace=argo workflow=hello-world-jjkd4
time="2020-01-09T10:53:39Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-jjkd4
time="2020-01-09T10:53:39Z" level=info msg="Updating node hello-world-jjkd4 (hello-world-jjkd4) message: ContainerCreating"
time="2020-01-09T10:53:39Z" level=info msg="Skipped pod hello-world-jjkd4 (hello-world-jjkd4) creation: already exists" namespace=argo workflow=hello-world-jjkd4
time="2020-01-09T10:53:39Z" level=info msg="Workflow update successful" namespace=argo workflow=hello-world-jjkd4
time="2020-01-09T10:53:40Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-jjkd4
time="2020-01-09T10:53:40Z" level=info msg="Skipped pod hello-world-jjkd4 (hello-world-jjkd4) creation: already exists" namespace=argo workflow=hello-world-jjkd4
time="2020-01-09T10:53:41Z" level=info msg="Processing workflow" namespace=argo workflow=hello-world-jjkd4
time="2020-01-09T10:53:41Z" level=info msg="Updating node hello-world-jjkd4 (hello-world-jjkd4) status Pending -> Error"
time="2020-01-09T10:53:41Z" level=info msg="Updating node hello-world-jjkd4 (hello-world-jjkd4) message: failed to save outputs: invalid configuration: no configuration has been provided"
time="2020-01-09T10:53:41Z" level=info msg="Updated phase Running -> Error" namespace=argo workflow=hello-world-jjkd4
time="2020-01-09T10:53:41Z" level=info msg="Updated message  -> failed to save outputs: invalid configuration: no configuration has been provided" namespace=argo workflow=hello-world-jjkd4
time="2020-01-09T10:53:41Z" level=info msg="Marking workflow completed" namespace=argo workflow=hello-world-jjkd4
time="2020-01-09T10:53:41Z" level=info msg="Checking daemoned children of " namespace=argo workflow=hello-world-jjkd4
time="2020-01-09T10:53:41Z" level=info msg="Workflow update successful" namespace=argo workflow=hello-world-jjkd4
time="2020-01-09T10:53:42Z" level=info msg="Labeled pod argo/hello-world-jjkd4 completed"
time="2020-01-09T10:57:56Z" level=info msg="Alloc=4638 TotalAlloc=21811 Sys=70078 NumGC=13 Goroutines=69"
```

**Comment by simster7** [comment]
See if this helps https://github.com/argoproj/argo/issues/838

**Comment by janhicken** [comment]
I am experiencing the same error. #838 does not help, as this is an issue with the CLI itself. The error shown here happens after the workflow has been submitted to Kubernetes successfully using the CLI. The workflow controller schedules the pod but the wait container fails as shown.

**Comment by janhicken** [comment]
Actually, it worked for me now, after setting `automountServiceAccountToken` to `true` for the pod's service account

**Comment by simster7** [comment]
Closing this, feel free to reopen if necesary

**Comment by mohan1005k** [comment]
@janhicken 

> Actually, it worked for me now, after setting automountServiceAccountToken to true for the pod's service account

`apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: hello
  templates:
    - name: hello
      container:
        image: XXXXX.dkr.ecr.us-west-2.amazonaws.com/nginx:latest
        command: [echo]
        args: ["hello"]
  nodeSelector:
    kubernetes.io/os: linux
  serviceAccountName: XXXX-XXXX
  automountServiceAccountToken:  true
  securityContext:
    fsGroup: 1602
    runAsUser: 1602
    runAsGroup: 1602
    runAsNonRoot: true
`
This is my workflow configuration, i still see the same issue even after adding automountServiceAccountToken: true. When i use a dummy service account it works fine. anything that am missing.?
