### ISSUE TITLE
Failure in pod with global output parameter breaks the workflow-controller and can't be terminated

### ISSUE THREAD

**Issue by samath117** [argoproj/argo#2083]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [x] I've included the logs.
 
**What happened**:

When a step which is supposed to product a global output parameter fails, it doesn't finish, cannot be terminated, and crashes the Argo workflow controller. The only way out I could find is to `argo delete` the workflow and recreate and rebuild the workflow-controller on the cluster.

**What you expected to happen**:

The step should just fail like any other step, with or without output parameters.

**How to reproduce it (as minimally and precisely as possible)**:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: failure-with-global-output-parameter-
spec:
  entrypoint: plan
  templates:
  - name: plan
    container:
      image: alpine:3.11
      command: [sh, -c]
      args: ["exit 1"]
    outputs:
      parameters:
      - name: message
        valueFrom:
          path: /test.txt
        globalName: message
```

This is a minimal example to demonstrate this failure mode. If the last line is removed, this fails as it should. But with the `globalName` present, the workflow-controller crashes.

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
$ argo version
argo: v2.4.1
  BuildDate: 2019-10-08T23:14:59Z
  GitCommit: d7f099992d8cf93c280df2ed38a0b9a1b2614e56
  GitTreeState: clean
  GitTag: v2.4.1
  GoVersion: go1.11.5
  Compiler: gc
  Platform: linux/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2019-08-19T11:13:54Z"
  compiler: gc
  gitCommit: 2d3c76f9091b6bec110a5e63777c332469e0cba2
  gitTreeState: clean
  gitVersion: v1.15.3
  goVersion: go1.12.9
  major: "1"
  minor: "15"
  platform: linux/amd64
serverVersion:
  buildDate: "2020-01-15T17:47:46Z"
  compiler: gc
  gitCommit: 2c6d0ee462cee7609113bf9e175c107599d5213f
  gitTreeState: clean
  gitVersion: v1.14.8-gke.33
  goVersion: go1.12.11b4
  major: "1"
  minor: 14+
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- workflow result:
```
argo get <workflowname>
Name:                failure-with-global-output-parameter-t5c8v
Namespace:           virtual
ServiceAccount:      default
Status:              Running
Created:             Tue Jan 28 14:09:26 -0500 (48 seconds ago)
Started:             Tue Jan 28 14:09:26 -0500 (48 seconds ago)
Duration:            48 seconds

STEP                                                  PODNAME                                     DURATION  MESSAGE
 ◷ failure-with-global-output-parameter-t5c8v (plan)  failure-with-global-output-parameter-t5c8v  48s       ContainerCreating
```
(note: sometimes it stays at ContainerCreating; sometimes it proceeds to Running, but it never finishes)

- executor logs:
```
kubectl logs <failedpodname> -c wait
time="2020-01-28T19:09:28Z" level=info msg="Creating a docker executor"
time="2020-01-28T19:09:28Z" level=info msg="Executor (version: v2.4.1, build_date: 2019-10-08T23:14:37Z) initialized (pod: virtual/failure-with-global-output-parameter-t5c8v) with template:\n{\"name\":\"plan\",\"arguments\":{},\"inputs\":{},\"outputs\":{\"parameters\":[{\"name\":\"message\",\"valueFrom\":{\"path\":\"/test.txt\"},\"globalName\":\"message\"}]},\"metadata\":{},\"container\":{\"name\":\"\",\"image\":\"alpine:3.11\",\"command\":[\"sh\",\"-c\"],\"args\":[\"exit 1\"],\"resources\":{}}}"
time="2020-01-28T19:09:28Z" level=info msg="Waiting on main container"
time="2020-01-28T19:09:28Z" level=info msg="main container started with container ID: 4b2cde2f392e4ad4542922041d325aec50e1805fcb93810b7130122e9223b7b4"
time="2020-01-28T19:09:28Z" level=info msg="Starting annotations monitor"
time="2020-01-28T19:09:28Z" level=info msg="docker wait 4b2cde2f392e4ad4542922041d325aec50e1805fcb93810b7130122e9223b7b4"
time="2020-01-28T19:09:28Z" level=info msg="Starting deadline monitor"
time="2020-01-28T19:09:28Z" level=info msg="Main container completed"
time="2020-01-28T19:09:28Z" level=info msg="Saving output parameters"
time="2020-01-28T19:09:28Z" level=info msg="Saving path output parameter: message"
time="2020-01-28T19:09:28Z" level=info msg="Copying /test.txt from base image layer"
time="2020-01-28T19:09:28Z" level=info msg="[sh -c docker cp -a 4b2cde2f392e4ad4542922041d325aec50e1805fcb93810b7130122e9223b7b4:/test.txt - | tar -ax -O]"
time="2020-01-28T19:09:28Z" level=info msg="Annotations monitor stopped"
time="2020-01-28T19:09:28Z" level=error msg="`[sh -c docker cp -a 4b2cde2f392e4ad4542922041d325aec50e1805fcb93810b7130122e9223b7b4:/test.txt - | tar -ax -O]` stderr:\nError: No such container:path: 4b2cde2f392e4ad4542922041d325aec50e1805fcb93810b7130122e9223b7b4:/test.txt\ntar: This does not look like a tar archive\ntar: Exiting with failure status due to previous errors\n"
time="2020-01-28T19:09:28Z" level=error msg="executor error: exit status 2\ngithub.com/argoproj/argo/errors.Wrap\n\t/go/src/github.com/argoproj/argo/errors/errors.go:88\ngithub.com/argoproj/argo/errors.InternalWrapError\n\t/go/src/github.com/argoproj/argo/errors/errors.go:71\ngithub.com/argoproj/argo/workflow/executor/docker.(*DockerExecutor).GetFileContents\n\t/go/src/github.com/argoproj/argo/workflow/executor/docker/docker.go:42\ngithub.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).SaveParameters\n\t/go/src/github.com/argoproj/argo/workflow/executor/executor.go:430\ngithub.com/argoproj/argo/cmd/argoexec/commands.waitContainer\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/commands/wait.go:44\ngithub.com/argoproj/argo/cmd/argoexec/commands.NewWaitCommand.func1\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/commands/wait.go:16\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/src/github.com/spf13/cobra/command.go:766\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/src/github.com/spf13/cobra/command.go:852\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/src/github.com/spf13/cobra/command.go:800\nmain.main\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/main.go:17\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:201\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1333"
time="2020-01-28T19:09:28Z" level=info msg="No output artifacts"
time="2020-01-28T19:09:28Z" level=info msg="Killing sidecars"
time="2020-01-28T19:09:28Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2020-01-28T19:09:28Z" level=info msg="Annotating pod with output"
time="2020-01-28T19:09:28Z" level=info msg="Alloc=4891 TotalAlloc=11775 Sys=69822 NumGC=4 Goroutines=9"
```
- workflow-controller logs (truncated, from another attempt):
```
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
time="2020-01-28T19:21:53Z" level=info msg="Processing workflow" namespace=virtual workflow=failure-with-global-output-parameter-stj7f
time="2020-01-28T19:21:53Z" level=info msg="Setting node failure-with-global-output-parameter-stj7f (failure-with-global-output-parameter-stj7f) outputs"
time="2020-01-28T19:21:53Z" level=info msg="Updating node failure-with-global-output-parameter-stj7f (failure-with-global-output-parameter-stj7f) status Pending -> Failed"
time="2020-01-28T19:21:53Z" level=info msg="Updating node failure-with-global-output-parameter-stj7f (failure-with-global-output-parameter-stj7f) message: exit status 2"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x134ce7b]

goroutine 104 [running]:
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).addParamToGlobalScope(0xc00011b3b0, 0xc0006eb200, 0x7, 0x0, 0x0, 0xc000131e40, 0xc0006eb359, 0x7)
        /go/src/github.com/argoproj/argo/workflow/controller/operator.go:1712 +0x1cb
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).addOutputsToScope(0xc00011b3b0, 0x16d5173, 0x8, 0xc000131e00, 0x0)
        /go/src/github.com/argoproj/argo/workflow/controller/operator.go:1610 +0x281
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).podReconciliation.func1(0xc0004a1c00)
        /go/src/github.com/argoproj/argo/workflow/controller/operator.go:599 +0x7a7
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).podReconciliation.func2(0xc0006ead00, 0xc0006cf980, 0xc00011b3b0, 0xc0006c5180, 0xc00002d0d0, 0xc00031f4a0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/argoproj/argo/workflow/controller/operator.go:625 +0xaf
created by github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).podReconciliation
        /go/src/github.com/argoproj/argo/workflow/controller/operator.go:623 +0x350
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
I'll close this as this doesn't appear to be an issue in 2.6. Please let me know if I'm wrong and I'll reopen
