### ISSUE TITLE
`make codegen` is very broken after `go mod` update.

### ISSUE THREAD

**Issue by simster7** [argoproj/argo#2245]
A couple of issues so far:

1.  When running `go-to-protobuf`, it errors out with the following:

```
topological order github.com/argoproj/argo/pkg/apis/workflow/v1alpha1
2020/02/18 08:48:20 /Users/sbeharyutk/go/src/k8s.io/kubernetes/vendor/github.com/gogo/protobuf/protobuf: warning: directory does not exist.
github.com/gogo/protobuf/gogoproto/gogo.proto: File not found.
k8s.io/apimachinery/pkg/util/intstr/generated.proto:8:1: Import "github.com/gogo/protobuf/gogoproto/gogo.proto" was not found or had errors.
2020/02/18 08:48:20 protoc -I . -I /Users/sbeharyutk/go/src -I /Users/sbeharyutk/go/src/k8s.io/kubernetes/vendor/github.com/gogo/protobuf/protobuf --gogo_out=/Users/sbeharyutk/go/src /Users/sbeharyutk/go/src/k8s.io/apimachinery/pkg/util/intstr/generated.proto
2020/02/18 08:48:20 Unable to generate protoc on k8s.io.apimachinery.pkg.util.intstr: exit status 1
make: *** [codegen] Error 1
```

https://github.com/argoproj/argo/blob/82b48821a83e012ac7ea5740d45addb046e3c8ee/hack/generate-proto.sh#L12-L15

The `k8s.io` dependencies in `go-to-protobuf` import `github.com/gogo/protobuf/gogoproto/gogo.proto`. This dependency used to be within `vendor/`; however, after the `go mod` update it is no longer there. In order to point `go-to-protobuf` to the correct location of the dependency, we add a `proto-import` flag:

```sh
go-to-protobuf \
    --go-header-file=./hack/custom-boilerplate.go.txt \
    --packages=github.com/argoproj/argo/pkg/apis/workflow/v1alpha1 \
    --apimachinery-packages=+k8s.io/apimachinery/pkg/util/intstr,+k8s.io/apimachinery/pkg/api/resource,k8s.io/apimachinery/pkg/runtime/schema,+k8s.io/apimachinery/pkg/runtime,k8s.io/apimachinery/pkg/apis/meta/v1,k8s.io/api/core/v1 \
    --proto-import ${GOPATH}/pkg/mod/
```

However, `go mod` versions the directories:

```sh
$ pwd
~/go/pkg/mod/github.com/gogo
$  ls
total 0
dr-x------  39 sbeharyutk  846622648  1248 Oct 15 08:21 protobuf@v1.1.1
dr-x------  42 sbeharyutk  846622648  1344 Jan 30 09:43 protobuf@v1.3.1
```

So `go-to-protobuf` still can't find them. A workaround: create a soft link:

```sh
$ ln -s protobuf\@v1.3.1/ protobuf
$ ls
total 0
lrwxr-xr-x   1 sbeharyutk  846622648    16 Feb 15 18:17 protobuf -> protobuf@v1.3.1/
dr-x------  39 sbeharyutk  846622648  1248 Oct 15 08:21 protobuf@v1.1.1
dr-x------  42 sbeharyutk  846622648  1344 Jan 30 09:43 protobuf@v1.3.1
```

This unblocks `go-to-protobuf`

2. `protoc` should import the modules instead of the specific package: `-I ${GOPATH}/pkg/mod` instead of `-I ${GOPATH}/pkg/mod/github.com/gogo/protobuf@v1.3.1/gogoproto`

3. `generate-groups.sh` inside `update-codegen.sh` seems to have internal bugs:

```sh
$ bash ~/go/pkg/mod/k8s.io/code-generator@v0.16.7-beta.0/generate-groups.sh deepcopy,client,informer,lister github.com/argoproj/argo/pkg/client github.com/argoproj/argo/pkg/apis workflow:v1alpha1 --go-header-file ./hack/custom-boilerplate.go.txt
Generating deepcopy funcs
Generating clientset for workflow:v1alpha1 at github.com/argoproj/argo/pkg/client/clientset
panic: runtime error: index out of range [1] with length 0

goroutine 275 [running]:
golang.org/x/tools/internal/imports.(*ModuleResolver).scanDirForPackage(0xc00aa30000, 0xc00ae00120, 0x1c, 0x4, 0xc00c4a3950, 0x41, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/sbeharyutk/go/pkg/mod/golang.org/x/tools@v0.0.0-20190821162956-65e3620a7ae7/internal/imports/mod.go:346 +0x990
golang.org/x/tools/internal/imports.(*ModuleResolver).scan.func1(0xc00ae00120, 0x1c, 0x4, 0xc00c4a3950, 0x41)
	/Users/sbeharyutk/go/pkg/mod/golang.org/x/tools@v0.0.0-20190821162956-65e3620a7ae7/internal/imports/mod.go:263 +0x73e
golang.org/x/tools/internal/gopathwalk.(*walker).walk(0xc0095e5940, 0xc00c4a3950, 0x50, 0x0, 0xc00c4a3950, 0x50)
	/Users/sbeharyutk/go/pkg/mod/golang.org/x/tools@v0.0.0-20190821162956-65e3620a7ae7/internal/gopathwalk/walk.go:175 +0xf3
golang.org/x/tools/internal/fastwalk.(*walker).onDirEnt(0xc00b879d10, 0xc00c517450, 0x41, 0xc00ba70fd0, 0xe, 0x0, 0x0, 0x0)
	/Users/sbeharyutk/go/pkg/mod/golang.org/x/tools@v0.0.0-20190821162956-65e3620a7ae7/internal/fastwalk/fastwalk.go:168 +0xbb
golang.org/x/tools/internal/fastwalk.readDir(0xc00c517450, 0x41, 0xc00b449e50, 0x0, 0x0)
	/Users/sbeharyutk/go/pkg/mod/golang.org/x/tools@v0.0.0-20190821162956-65e3620a7ae7/internal/fastwalk/fastwalk_unix.go:68 +0x21e
golang.org/x/tools/internal/fastwalk.(*walker).walk(0xc00b879d10, 0xc00c517450, 0x41, 0x1, 0x1, 0x0)
	/Users/sbeharyutk/go/pkg/mod/golang.org/x/tools@v0.0.0-20190821162956-65e3620a7ae7/internal/fastwalk/fastwalk.go:195 +0x6a
golang.org/x/tools/internal/fastwalk.(*walker).doWork(0xc00b879d10, 0xc00bb641b0)
	/Users/sbeharyutk/go/pkg/mod/golang.org/x/tools@v0.0.0-20190821162956-65e3620a7ae7/internal/fastwalk/fastwalk.go:134 +0x175
created by golang.org/x/tools/internal/fastwalk.Walk
	/Users/sbeharyutk/go/pkg/mod/golang.org/x/tools@v0.0.0-20190821162956-65e3620a7ae7/internal/fastwalk/fastwalk.go:81 +0x248
```

**Comment by alexec** [comment]
```
      --proto-import strings           The search path for the core protobuf .protos, required; defaults $GOPATH/src/k8s.io/kubernetes/vendor/github.com/gogo/protobuf/protobuf. (default [/Users/acollins8/go/src/k8s.io/kubernetes/vendor/github.com/gogo/protobuf/protobuf])
```

**Comment by simster7** [comment]
> `      --proto-import strings           The search path for the core protobuf .protos, required; defaults $GOPATH/src/k8s.io/kubernetes/vendor/github.com/gogo/protobuf/protobuf. (default [/Users/acollins8/go/src/k8s.io/kubernetes/vendor/github.com/gogo/protobuf/protobuf])`

Yes, I mention that in the issue.

The current workaround is to run `go mod vendor` to generate a vendor file and point both `go-to-protoc` and `protoc` to it

**Comment by simster7** [comment]
Seems to be fixed on master
