### ISSUE TITLE
Minion-manager crashes when no asgs are configured

### ISSUE THREAD

**Issue by shrinandj** [argoproj/argo#279]
```
2017-09-25T22:28:43 INFO minion_manager MainThread: Starting ...
2017-09-25T22:28:43 INFO minion_manager MainThread: Using config from env: us-west-2
2017-09-25T22:28:43 INFO minion_manager MainThread: Using config from env: None
Traceback (most recent call last):
  File "/ax/bin/minion_manager", line 91, in <module>
    run()
  File "/ax/bin/minion_manager", line 71, in run
    validate_usr_args(usr_args)
  File "/ax/bin/minion_manager", line 32, in validate_usr_args
    "At least 1 scaling group is needed"
AssertionError: At least 1 scaling group is needed
```

**Comment by shrinandj** [comment]
Fixed with the following commit on master:

```
commit 4d30a3c725aa2b599df79756bc7f7c3e8628dcd9
Author: Shri Javadekar <shrinand@applatix.com>
Date:   Mon Oct 2 09:25:57 2017 -0700

    Start minion-manager correctly with the "no spot" option.

```

And on v1.0
```
commit 4c00d5ddb0442b36cfd87a3fa8a25024b11971f0
Author: Shri Javadekar <shrinand@applatix.com>
Date:   Mon Oct 2 09:25:57 2017 -0700

    Start minion-manager correctly with the "no spot" option.

...
```
