### ISSUE TITLE
Investigate cron controller panic

### ISSUE THREAD

**Issue by alexec** [argoproj/argo#2952]
Panics result in controller restart and therefore loss of service. We should investigate this.

```
time="2020-05-02T20:50:00Z" level=info msg="Pod node {canary-glmcm canary-glmcm canary-glmcm Pod whalesay nil   local/canary-glmcm Pending   2020-05-02 20:50:00.553640018 +0000 UTC 0001-01-01 00:00:00 +0000 UTC   <nil> nil nil [] []} initialized Pending" namespace=argo workflow=canary-glmcm
time="2020-05-02T20:50:00Z" level=info msg="Processing argo/canary"
fatal error: concurrent map read and map write
goroutine 86 [running]:
runtime.throw(0x185b3b0, 0x21)
	/usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc000573ae8 sp=0xc000573ab8 pc=0x42e5d2
runtime.mapaccess2_faststr(0x1614e60, 0xc00043b6b0, 0xc004b2a2c0, 0x3c, 0x1, 0xc0057482a0)
	/usr/local/go/src/runtime/map_faststr.go:116 +0x48f fp=0xc000573b58 sp=0xc000573ae8 pc=0x412cff
github.com/argoproj/argo/workflow/cron.(*Controller).processNextWorkflowItem(0xc0000e2580, 0xc00047fe00)
	/go/src/github.com/argoproj/argo/workflow/cron/controller.go:222 +0x45d fp=0xc000573e38 sp=0xc000573b58 pc=0x14567fd
```

**Comment by alexec** [comment]
@simster7 this appears to be in the cron code - would you own the investigate please?

**Comment by simster7** [comment]
Could you make sure that the branch you're working on has this fix https://github.com/argoproj/argo/pull/2851 in it?

**Comment by simster7** [comment]
The line in the stack trace:
```
workflow/cron/controller.go:222
```
Only points to a relevant line in a version of the file without the fix, leading me to believe you don't have it merged

**Comment by alexec** [comment]
This is old - so probaly fixed. Thank you.
