### ISSUE TITLE
Fix panics

### ISSUE THREAD

**Issue by alexec** [argoproj/argo#3118]
```
 controller | time="2020-05-27T23:58:02Z" level=warning msg="Error updating workflow: Operation cannot be fulfilled on workflows.argoproj.io \"test-cron-wf-basic-mj5bn\": StorageError: invalid object, Code: 4, Key: /registry/argoproj.io/workflows/argo/test-cron-wf-basic-mj5bn, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 73299ac8-7de4-48b5-b25d-ef1941ad8d2e, UID in object meta:  Conflict" namespace=argo workflow=test-cron-wf-basic-mj5bn
 controller | time="2020-05-27T23:58:02Z" level=info msg="Re-applying updates on latest version and retrying update" namespace=argo workflow=test-cron-wf-basic-mj5bn
 controller | E0527 23:58:02.422603   19236 runtime.go:76] Observed a panic: original workflow is not hydrated
 controller | goroutine 271 [running]:
 controller | k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1628e80, 0x1ac7d80)
```

https://app.circleci.com/pipelines/github/argoproj/argo/4080/workflows/575ce35b-ed70-4512-bc31-2670d3fc51fc/jobs/25086/steps

**Comment by alexec** [comment]
```
 controller | time="2020-05-22T03:33:44Z" level=error msg="getting offloaded nodes failed: upper: no more rows in this result set" namespace=argo workflow=workflow-template-hello-world-v8lqd
 controller | time="2020-05-22T03:33:44Z" level=info msg="Updated phase Running -> Error" namespace=argo workflow=workflow-template-hello-world-v8lqd
 controller | time="2020-05-22T03:33:44Z" level=info msg="Updated message  -> upper: no more rows in this result set" namespace=argo workflow=workflow-template-hello-world-v8lqd
 controller | time="2020-05-22T03:33:44Z" level=info msg="Marking workflow completed" namespace=argo workflow=workflow-template-hello-world-v8lqd
 controller | E0522 03:33:44.298546   15107 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
 controller | goroutine 278 [running]:
 controller | k8s.io/apimachinery/pkg/util/runtime.logPanic(0x16a5340, 0x272e0f0)
 controller | 	/home/circleci/.go_workspace/pkg/mod/k8s.io/apimachinery@v0.16.7-beta.0/pkg/util/runtime/runtime.go:74 +0xa3
 controller | k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
 controller | 	/home/circleci/.go_workspace/pkg/mod/k8s.io/apimachinery@v0.16.7-beta.0/pkg/util/runtime/runtime.go:48 +0x82
 controller | panic(0x16a5340, 0x272e0f0)
 controller | 	/home/circleci/sdk/go1.13.4/src/runtime/panic.go:679 +0x1b2
 controller | github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).deletePDBResource(0xc000458240, 0x18a4526, 0x9)
 controller | 	/home/circleci/.go_workspace/src/github.com/argoproj/argo/workflow/controller/operator.go:2643 +0x41
 controller | github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).markWorkflowPhase(0xc000458240, 0x18a121f, 0x5, 0x1, 0xc000bad938, 0x1, 0x1)
 controller | 	/home/circleci/.go_workspace/src/github.com/argoproj/argo/workflow/controller/operator.go:1643 +0x639
 controller | github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).markWorkflowError(0xc000458240, 0x1ae1480, 0xc000559f10, 0x1)
 controller | 	/home/circleci/.go_workspace/src/github.com/argoproj/argo/workflow/controller/operator.go:1681 +0x99
 controller | github.com/argoproj/argo/workflow/controller.(*WorkflowController).processNextItem(0xc00035ce00, 0xc0005a1e00)
 controller | 	/home/circleci/.go_workspace/src/github.com/argoproj/argo/workflow/controller/controller.go:433 +0xfd7
 controller | github.com/argoproj/argo/workflow/controller.(*WorkflowController).runWorker(0xc00035ce00)
 controller | 	/home/circleci/.go_workspace/src/github.com/argoproj/argo/workflow/controller/controller.go:364 +0x2b
 controller | k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000ad6410)
 controller | 	/home/circleci/.go_workspace/pkg/mod/k8s.io/apimachinery@v0.16.7-beta.0/pkg/util/wait/wait.go:152 +0x5e
 controller | k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000ad6410, 0x3b9aca00, 0x0, 0x1, 0xc000049860)
 controller | 	/home/circleci/.go_workspace/pkg/mod/k8s.io/apimachinery@v0.16.7-beta.0/pkg/util/wait/wait.go:153 +0xf8
 controller | k8s.io/apimachinery/pkg/util/wait.Until(0xc000ad6410, 0x3b9aca00, 0xc000049860)
 controller | 	/home/circleci/.go_workspace/pkg/mod/k8s.io/apimachinery@v0.16.7-beta.0/pkg/util/wait/wait.go:88 +0x4d
 controller | created by github.com/argoproj/argo/workflow/controller.(*WorkflowController).Run
 controller | 	/home/circleci/.go_workspace/src/github.com/argoproj/argo/workflow/controller/controller.go:177 +0x9cd
 controller | panic: runtime error: invalid memory address or nil pointer dereference [recovered]
 controller | 	panic: runtime error: invalid memory address or nil pointer dereference
 controller | [signal SIGSEGV: segmentation violation code=0x1 addr=0x1a8 pc=0x151a1e1]
 controller | goroutine 278 [running]:
 controller | k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
 controller | 	/home/circleci/.go_workspace/pkg/mod/k8s.io/apimachinery@v0.16.7-beta.0/pkg/util/runtime/runtime.go:55 +0x105
 controller | panic(0x16a5340, 0x272e0f0)
 controller | 	/home/circleci/sdk/go1.13.4/src/runtime/panic.go:679 +0x1b2
 controller | github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).deletePDBResource(0xc000458240, 0x18a4526, 0x9)
 controller | 	/home/circleci/.go_workspace/src/github.com/argoproj/argo/workflow/controller/operator.go:2643 +0x41
 controller | github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).markWorkflowPhase(0xc000458240, 0x18a121f, 0x5, 0x1, 0xc000bad938, 0x1, 0x1)
 controller | 	/home/circleci/.go_workspace/src/github.com/argoproj/argo/workflow/controller/operator.go:1643 +0x639
 controller | github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).markWorkflowError(0xc000458240, 0x1ae1480, 0xc000559f10, 0x1)
 controller | 	/home/circleci/.go_workspace/src/github.com/argoproj/argo/workflow/controller/operator.go:1681 +0x99
 controller | github.com/argoproj/argo/workflow/controller.(*WorkflowController).processNextItem(0xc00035ce00, 0xc0005a1e00)
 controller | 	/home/circleci/.go_workspace/src/github.com/argoproj/argo/workflow/controller/controller.go:433 +0xfd7
 controller | github.com/argoproj/argo/workflow/controller.(*WorkflowController).runWorker(0xc00035ce00)
 controller | 	/home/circleci/.go_workspace/src/github.com/argoproj/argo/workflow/controller/controller.go:364 +0x2b
 controller | k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000ad6410)
 controller | 	/home/circleci/.go_workspace/pkg/mod/k8s.io/apimachinery@v0.16.7-beta.0/pkg/util/wait/wait.go:152 +0x5e
 controller | k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000ad6410, 0x3b9aca00, 0x0, 0x1, 0xc000049860)
 controller | 	/home/circleci/.go_workspace/pkg/mod/k8s.io/apimachinery@v0.16.7-beta.0/pkg/util/wait/wait.go:153 +0xf8
 controller | k8s.io/apimachinery/pkg/util/wait.Until(0xc000ad6410, 0x3b9aca00, 0xc000049860)
 controller | 	/home/circleci/.go_workspace/pkg/mod/k8s.io/apimachinery@v0.16.7-beta.0/pkg/util/wait/wait.go:88 +0x4d
 controller | created by github.com/argoproj/argo/workflow/controller.(*WorkflowController).Run
 controller | 	/home/circleci/.go_workspace/src/github.com/argoproj/argo/workflow/controller/controller.go:177 +0x9cd
 controller | Terminating controller
```

Unrelated?

https://app.circleci.com/pipelines/github/argoproj/argo/3980/workflows/1a112bdc-1b81-49ac-b809-a40b7124d798/jobs/24225/steps

**Comment by alexec** [comment]
We should never see `upper: no more rows in this result set`.

**Comment by alexec** [comment]
Second error is pre-hydrator - so ignoring.
