### ISSUE TITLE
axmon crashes for aws cloud install of argo using latest master branch code

### ISSUE THREAD

**Issue by sandeepbhojwani** [argoproj/argo#329]
2017-10-10T16:38:30 ERROR AXmon DummyThread-1029: Environment ARGO_S3_ACCESS_KEY_ID in container axsidekickwait needs to have a valid value/value_from/value_from_secret
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/ax/python/ax/platform/rest.py", line 502, in task_create
    return jsonify(result=axmon.task_create(data))
  File "/ax/python/ax/platform/axmon_main.py", line 78, in task_create
    job_obj = task.create(conf)
  File "/ax/python/ax/platform/task.py", line 107, in create
    template_spec = self._container_to_pod(labels)
  File "/ax/python/ax/platform/task.py", line 246, in _container_to_pod
    wait_container = self._generate_wait_container_spec()
  File "/ax/python/ax/platform/task.py", line 355, in _generate_wait_container_spec
    c.add_env("ARGO_S3_ACCESS_KEY_ID", os.environ.get("ARGO_S3_ACCESS_KEY_ID"))
  File "/ax/python/ax/platform/container.py", line 256, in add_env
    raise ValueError("Environment {} in container {} needs to have a valid value/value_from/value_from_secret".format(name, self.name))
ValueError: Environment ARGO_S3_ACCESS_KEY_ID in container axsidekickwait needs to have a valid value/value_from/value_from_secret

**Comment by shrinandj** [comment]
Fixed with 306c79f.
