### ISSUE TITLE
Argo on minikube fails during installation because "region" is not set

### ISSUE THREAD

**Issue by shrinandj** [argoproj/argo#343]
Installation of Argo on minikube fails because the "region" is not set and thereby the AX_AWS_REGION env variable is not set.

```
ConnectionError: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/meta-data/placement/availability-zone (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f7640d81c90>: Failed to establish a new connection: [Errno 101] Network unreachable',))
Traceback (most recent call last):
  File "/ax/bin/axmon", line 57, in <module>
    axmon_rest_start(port=args.port)
  File "/ax/python/ax/platform/rest.py", line 1021, in axmon_rest_start
    axmon = AXMon()
  File "/ax/python/ax/util/singleton.py", line 15, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/ax/python/ax/platform/axmon_main.py", line 61, in __init__
    VolumeManager()
  File "/ax/python/ax/platform/volumes.py", line 676, in __call__
    cls._instances[namespace] = super(VolumeManagerSingleton, cls).__call__(namespace)
  File "/ax/python/ax/platform/volumes.py", line 705, in __init__
    self.ec2 = boto3.Session().client('ec2', region_name=get_region())
  File "/ax/python/ax/platform/volumes.py", line 704, in get_region
    return AWSMetaData().get_region() if AXEnv().is_in_pod() else "us-west-2"
  File "/ax/python/ax/aws/meta_data.py", line 36, in get_region
    return r.text[:-1]
```

**Comment by shrinandj** [comment]
Fixed with 1aa888c.
