### ISSUE TITLE
TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by alexec** [argoproj/argo#3550]
Open the workflow page and try to filter by label:

```
TypeError: Cannot read property 'push' of undefined
    at http://localhost:8080/main.3cfef717cae1429b490c.js:348152:39
    at Array.forEach (<anonymous>)
    at WorkflowsList../src/app/workflows/components/workflows-list/workflows-list.tsx.WorkflowsList.changeFilters (http://localhost:8080/main.3cfef717cae1429b490c.js:348150:24)
    at Object.onChange (http://localhost:8080/main.3cfef717cae1429b490c.js:348062:46)
    at Object.onChange (http://localhost:8080/main.3cfef717cae1429b490c.js:346729:41)
    at TagsInput../src/app/shared/components/tags-input/tags-input.tsx.TagsInput.onTagsChange (http://localhost:8080/main.3cfef717cae1429b490c.js:343647:24)
    at Object.onSelect (http://localhost:8080/main.3cfef717cae1429b490c.js:343607:31)
    at Autocomplete.<anonymous> (http://localhost:8080/main.3cfef717cae1429b490c.js:239509:22)
    at callCallback (http://localhost:8080/main.3cfef717cae1429b490c.js:256661:12)
    at commitUpdateEffects (http://localhost:8080/main.3cfef717cae1429b490c.js:256700:7)
```

**Comment by rbreeze** [comment]
Fixed in #3555.
