### ISSUE TITLE
argo installation fails for user provided cluster with some existing namespaces

### ISSUE THREAD

**Issue by sandeepbhojwani** [argoproj/argo#357]
tested this on minikube where if i have a namespace that is not an argo namespace, install fails...

axopsbootstrap: [{'reason': u'SuccessfulMountVolume', 'message': u'MountVolume.SetUp succeeded for volume "default-token-j30rt" ', 'name': u'axops-bootstrap-pod'}]

==============================

2017-10-12T17:18:25 INFO ax.platform.platform MainThread: Updating application managers
2017-10-12T17:18:25 INFO ax.platform.platform MainThread: --- updating argos3
2017-10-12T17:18:25 ERROR ax.cluster_management.app.cluster_installer MainThread: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/ax/python/ax/cluster_management/app/cluster_installer.py", line 271, in install_and_run_platform
    platform.start()
  File "/ax/python/ax/platform/platform.py", line 335, in start
    a = Application(app, client=self.kubectl)
  File "/ax/python/ax/platform/application.py", line 52, in __init__
    elb_status = elb.status(with_loadbalancer_info=True)["loadbalancer"][0]
TypeError: 'NoneType' object has no attribute '__getitem__'
2017-10-12T17:18:25 ERROR ax.cluster_management.argo_cluster_manager MainThread: 'NoneType' object has no attribute '__getitem__'
Please manually check the cluster status and retry installation with same command if the error is transient.
Traceback (most recent call last):
  File "/ax/python/ax/cluster_management/argo_cluster_manager.py", line 77, in parse_args_and_run
    getattr(self, cmd)(args)
  File "/ax/python/ax/cluster_management/argo_cluster_manager.py", line 246, in install_platform_only
    PlatformOnlyInstaller(platform_install_config).run()
  File "/ax/python/ax/cluster_management/app/cluster_installer.py", line 527, in run
    cluster_dns, username, password = self._ci_installer.install_and_run_platform()
  File "/ax/python/ax/cluster_management/app/cluster_installer.py", line 279, in install_and_run_platform
    raise RuntimeError(install_platform_failure_message)
RuntimeError: 'NoneType' object has no attribute '__getitem__'
Please manually check the cluster status and retry installation with same command if the error is transient.

 !!! Operation failed due to runtime error: 'NoneType' object has no attribute '__getitem__'
Please manually check the cluster status and retry installation with same command if the error is transient.

**Comment by shrinandj** [comment]
Fixed with 7a3ca2a08a05a77616d4511441670dff0e300c3d.
