### ISSUE TITLE
argo-lite: log download failed with error.

### ISSUE THREAD

**Issue by hphsu** [argoproj/argo#378]
Download any workflow log from argo-lite failed with following message:

TypeError: Cannot read property 'split' of undefined
    at app.get (/app/dist/main.js:106:47)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at jsonParser (/app/node_modules/body-parser/lib/types/json.js:109:7)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)

**Comment by alexmt** [comment]
Thanks for catching it! Fixing
