### ISSUE TITLE
Install Argo on Minikube failing with permission issue

### ISSUE THREAD

**Issue by mukulikak** [argoproj/argo#389]
Argo install on Minikube failing

-----

**argo cluster ops> argocluster install-argo-only --cluster-name minikube --kubeconfig /tmp/ax_kube/argo_cluster_inline-minikube.conf --cloud-provider minikube**
2017-10-19T19:52:41 INFO ax.cluster_management.argo_cluster_manager MainThread: Installing Argo platform ...
2017-10-19T19:52:41 INFO ax.cluster_management.argo_cluster_manager MainThread: Installing s3 proxy ...
namespace "axs3" created
persistentvolumeclaim "s3proxy-pvc" created
service "s3proxy" created
deployment "s3proxy-deployment" created
2017-10-19T19:52:43 INFO ax.cluster_management.argo_cluster_manager MainThread: Creating s3 bucket using location: http://192.168.99.100:31791/argo
2017-10-19T19:52:50 INFO ax.cluster_management.argo_cluster_manager MainThread: Creating s3 bucket using location: http://192.168.99.100:31791/argo
2017-10-19T19:53:02 INFO ax.cluster_management.argo_cluster_manager MainThread: Creating s3 bucket using location: http://192.168.99.100:31791/argo
2017-10-19T19:53:26 INFO ax.cluster_management.argo_cluster_manager MainThread: Creating s3 bucket using location: http://192.168.99.100:31791/argo
2017-10-19T19:53:27 INFO ax.cluster_management.argo_cluster_manager MainThread: s3 bucket endpoint: http://192.168.99.100:31791
2017-10-19T19:53:27 INFO ax.meta.cluster_id MainThread: Instantiating cluster bucket ...
2017-10-19T19:53:32 INFO ax.cloud.aws.aws_s3 MainThread: Using region None for bucket argo
2017-10-19T19:53:32 INFO ax.meta.cluster_id MainThread: Cannot find cluster name/id mapping from bucket
2017-10-19T19:53:32 INFO ax.cluster_management.app.common MainThread: Cannot find cluster name id: Failed to load cluster name and cluster id from bucket. Cluster is not yet created.
2017-10-19T19:53:32 INFO ax.meta.cluster_id MainThread: Cluster id not provided, generate one.
2017-10-19T19:53:32 INFO ax.meta.cluster_id MainThread: Created new name-id minikube-2fcc70fc-b507-11e7-b250-025000000001
2017-10-19T19:53:32 INFO ax.meta.config_s3_path MainThread: Using AX cluster config path argo
2017-10-19T19:53:33 INFO ax.cloud.aws.aws_s3 MainThread: Using region None for bucket argo
2017-10-19T19:53:33 INFO ax.cloud.aws.aws_s3 MainThread: Using region None for bucket argo
2017-10-19T19:53:33 INFO ax.platform.ax_cluster_info MainThread: Downloading cluster current state ...
2017-10-19T19:53:33 INFO ax.platform.cluster_buckets MainThread: Creating and updating all cluster buckets ...
2017-10-19T19:53:33 INFO ax.cloud.aws.aws_s3 MainThread: Using region None for bucket argo
2017-10-19T19:53:34 INFO ax.cloud.aws.aws_s3 MainThread: Bucket argo already exist, don't create.
2017-10-19T19:53:34 INFO ax.platform.cluster_buckets MainThread: Created argo bucket ... DONE
2017-10-19T19:53:34 INFO ax.meta.config_s3_path MainThread: Using AX cluster data path argo
2017-10-19T19:53:34 INFO ax.cloud.aws.aws_s3 MainThread: Using region None for bucket argo
2017-10-19T19:53:34 INFO ax.cloud.aws.aws_s3 MainThread: Bucket argo already exist, don't create.
2017-10-19T19:53:34 INFO ax.platform.cluster_buckets MainThread: Created argo bucket ... DONE
2017-10-19T19:53:34 INFO ax.platform.cluster_buckets MainThread: Creating and updating all cluster buckets ... DONE
2017-10-19T19:53:34 INFO ax.platform.ax_cluster_info MainThread: Setting kube_config to /tmp/ax_kube/argo_cluster_inline-minikube.conf
2017-10-19T19:53:35 ERROR ax.cluster_management.argo_cluster_manager MainThread: An error occurred (AccessDenied) when calling the AssumeRole operation: Not authorized to perform sts:AssumeRole
Traceback (most recent call last):
  File "/ax/python/ax/cluster_management/argo_cluster_manager.py", line 86, in parse_args_and_run
    getattr(self, cmd)(args)
  File "/ax/python/ax/cluster_management/argo_cluster_manager.py", line 265, in install_argo_only
    PlatformOnlyInstaller(platform_install_config).run()
  File "/ax/python/ax/cluster_management/app/cluster_installer.py", line 525, in run
    cloud_provider=self._cfg.cloud_provider)
  File "/ax/python/ax/cluster_management/app/cluster_installer.py", line 498, in update_and_save_config
    raw_cluster_config_dict = self._generate_raw_cluster_config_dict()
  File "/ax/python/ax/cluster_management/app/cluster_installer.py", line 408, in _generate_raw_cluster_config_dict
    return self._generate_raw_cluster_config_dict_aws(config)
  File "/ax/python/ax/cluster_management/app/cluster_installer.py", line 474, in _generate_raw_cluster_config_dict_aws
    aws_region=self._cfg.cloud_region
  File "/ax/python/ax/cloud/aws/ami.py", line 22, in __init__
    self._amicli = boto3.Session(region_name=aws_region, profile_name=aws_profile).client("ec2")
  File "/usr/local/lib/python2.7/dist-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python2.7/dist-packages/botocore/session.py", line 825, in create_client
    credentials = self.get_credentials()
  File "/usr/local/lib/python2.7/dist-packages/botocore/session.py", line 449, in get_credentials
    'credential_provider').load_credentials()
  File "/usr/local/lib/python2.7/dist-packages/botocore/credentials.py", line 1146, in load_credentials
    creds = provider.load()
  File "/usr/local/lib/python2.7/dist-packages/botocore/credentials.py", line 842, in load
    return self._load_creds_via_assume_role()
  File "/usr/local/lib/python2.7/dist-packages/botocore/credentials.py", line 861, in _load_creds_via_assume_role
    creds, response = self._retrieve_temp_credentials()
  File "/usr/local/lib/python2.7/dist-packages/botocore/credentials.py", line 970, in _retrieve_temp_credentials
    response = client.assume_role(**assume_role_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 312, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 601, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (AccessDenied) when calling the AssumeRole operation: Not authorized to perform sts:AssumeRole

 !!! Operation failed due to runtime error: An error occurred (AccessDenied) when calling the AssumeRole operation: Not authorized to perform sts:AssumeRole 

--------
My env is

argo cluster ops> env | grep ARGO
ARGO_DIST_REGISTRY_SECRETS=
ARGO_DIST_REGISTRY=docker.io
argo cluster ops> env | grep AX  
AX_NAMESPACE=argoproj
AX_VERSION=latest
AX_AWS_IMAGE_NAME=k8s-1.6-debian-jessie-amd64-hvm-ebs-2017-05-02
AX_KUBERNETES_ROOT=/kubernetes
AX_KUBE_VERSION=1.6.7
argo cluster ops> 

[argo_cluster_inline-minikube.txt](https://github.com/argoproj/argo/files/1399823/argo_cluster_inline-minikube.txt)

**Comment by shrinandj** [comment]
Fixed with 64c2698.
