### ISSUE TITLE
ClientError: An error occurred (403) when calling the HeadBucket operation: Forbidden

### ISSUE THREAD

**Issue by francis-ax** [argoproj/argo#394]
Installed t2.eng.test.applatix.net (in dev account) on existing kubernetes and started CI workflow on it.
However all of the job stuck in queue, axmon log show it run into bucket region related issue again..

```
Francis-Macbook-Pro:.kube francis$ kpassword
ClusterID: t2.test.eng.applatix.net
Access info in ~/.argo

Francis-Macbook-Pro:.kube francis$ kl axmon-deployment-3775411424-vvvln axmon --tail 50
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/lib/python2.7/site-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/lib/python2.7/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/lib/python2.7/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/ax/python/ax/cloud/aws/aws_s3.py", line 565, in _exists
    raise ce
ClientError: An error occurred (403) when calling the HeadBucket operation: Forbidden
::ffff:100.96.1.12 - - [2017-10-20 16:03:14] "POST /v1/axmon/task HTTP/1.1" 400 2070 7.963166
2017-10-20T16:03:14 DEBUG ax.cloud.aws.aws_s3 DummyThread-151: Finding region for bucket applatixtest3 from with initial region us-west-2
2017-10-20T16:03:14 DEBUG ax.cloud.aws.aws_s3 DummyThread-152: Finding region for bucket applatixtest3 from with initial region us-west-2
2017-10-20T16:03:14 DEBUG ax.cloud.aws.aws_s3 DummyThread-153: Finding region for bucket applatixtest3 from with initial region us-west-2
2017-10-20T16:03:14 DEBUG ax.cloud.aws.aws_s3 DummyThread-152: Head_bucket returned error {'ResponseMetadata': {'HTTPStatusCode': 403, 'RetryAttempts': 0, 'HostId': 'JR3rnsJQNMnRigjBLGUyOJQEPzxbWrObbQRjUERKH51zP4zGiYyXTswFLJEEcahXSHaFp/8BFQc=', 'RequestId': '07F7F9AE6CC8BC8E', 'HTTPHeaders': {'date': 'Fri, 20 Oct 2017 16:03:13 GMT', 'x-amz-id-2': 'JR3rnsJQNMnRigjBLGUyOJQEPzxbWrObbQRjUERKH51zP4zGiYyXTswFLJEEcahXSHaFp/8BFQc=', 'server': 'AmazonS3', 'transfer-encoding': 'chunked', 'x-amz-request-id': '07F7F9AE6CC8BC8E', 'x-amz-bucket-region': 'us-west-2', 'content-type': 'application/xml'}}, 'Error': {'Message': 'Forbidden', 'Code': '403'}}, inspecting headers
2017-10-20T16:03:14 INFO ax.cloud.aws.aws_s3 DummyThread-152: Using region None for bucket applatixtest3
2017-10-20T16:03:14 DEBUG ax.cloud.aws.aws_s3 DummyThread-151: Head_bucket returned error {'ResponseMetadata': {'HTTPStatusCode': 403, 'RetryAttempts': 0, 'HostId': 'VY0Y1Cx1xA/8IS0AO8+ML3PGD3mk4N1QfX72tA8DtuJFpUATjdRqjMl16bHqwRul32J1OdD8DS4=', 'RequestId': '74B3AC4E24D8969D', 'HTTPHeaders': {'date': 'Fri, 20 Oct 2017 16:03:14 GMT', 'x-amz-id-2': 'VY0Y1Cx1xA/8IS0AO8+ML3PGD3mk4N1QfX72tA8DtuJFpUATjdRqjMl16bHqwRul32J1OdD8DS4=', 'server': 'AmazonS3', 'transfer-encoding': 'chunked', 'x-amz-request-id': '74B3AC4E24D8969D', 'x-amz-bucket-region': 'us-west-2', 'content-type': 'application/xml'}}, 'Error': {'Message': 'Forbidden', 'Code': '403'}}, inspecting headers
2017-10-20T16:03:14 INFO ax.cloud.aws.aws_s3 DummyThread-151: Using region None for bucket applatixtest3
2017-10-20T16:03:14 ERROR AXmon DummyThread-150: Internal error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/ax/python/ax/platform/rest.py", line 515, in task_show
    return jsonify(result=axmon.task_show(task_id))
  File "/ax/python/ax/platform/axmon_main.py", line 85, in task_show
    task = Task(task_id)
  File "/ax/python/ax/platform/task.py", line 79, in __init__
    self._s3_bucket_ax_is_external = AXLogPath(self._name_id).is_external()
  File "/ax/python/ax/meta/config_s3_path.py", line 230, in __new__
    if AXSupportConfigPath(name_id).bucket_exists():
  File "/ax/python/ax/meta/config_s3_path.py", line 68, in bucket_exists
    self._bucket_exists = Cloud().get_bucket(self._bucket_name).exists()
  File "/ax/python/ax/cloud/aws/aws_s3.py", line 285, in exists
    return self._exists()
  File "/usr/lib/python2.7/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/lib/python2.7/site-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/lib/python2.7/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/lib/python2.7/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/ax/python/ax/cloud/aws/aws_s3.py", line 565, in _exists
    raise ce
ClientError: An error occurred (403) when calling the HeadBucket operation: Forbidden
::ffff:100.96.1.12 - - [2017-10-20 16:03:14] "GET /v1/axmon/task/axworkflowexecutor-452e02dd-b5af-11e7-86f8-0a5864600106 HTTP/1.1" 400 2067 7.417790
2017-10-20T16:03:14 DEBUG ax.cloud.aws.aws_s3 DummyThread-153: Head_bucket returned error {'ResponseMetadata': {'HTTPStatusCode': 403, 'RetryAttempts': 0, 'HostId': 'cx7PdapQI4lpluqEBLVAiB6pN+MM5/ZzqjUBIq1acjVbQwtjWeemoZuZ+/Fvz3SpCrT7yiS639U=', 'RequestId': '897488F2E253B9CD', 'HTTPHeaders': {'date': 'Fri, 20 Oct 2017 16:03:13 GMT', 'x-amz-id-2': 'cx7PdapQI4lpluqEBLVAiB6pN+MM5/ZzqjUBIq1acjVbQwtjWeemoZuZ+/Fvz3SpCrT7yiS639U=', 'server': 'AmazonS3', 'transfer-encoding': 'chunked', 'x-amz-request-id': '897488F2E253B9CD', 'x-amz-bucket-region': 'us-west-2', 'content-type': 'application/xml'}}, 'Error': {'Message': 'Forbidden', 'Code': '403'}}, inspecting headers
2017-10-20T16:03:14 INFO ax.cloud.aws.aws_s3 DummyThread-153: Using region None for bucket applatixtest3
```

**Comment by shrinandj** [comment]
This is a problem with the way the minions IAM role is setup. In the IAM statement, you need both the lines below:

```
                "arn:aws:s3:::applatixtest3",
                "arn:aws:s3:::applatixtest3/*",
```

The documentation will reflect this.

**Comment by shrinandj** [comment]
After making the above mentioned IAM role changes, things have worked fine. Closing this now.
