### ISSUE TITLE
GKE Installation failed

### ISSUE THREAD

**Issue by mukulikak** [argoproj/argo#406]
Log below. What am i doing wrong?

-----
```
argo cluster ops> argocluster install-argo-only --cloud-provider gke --cluster-name cluster-1 --kubeconfig /tmp/ax_kube/argo-gke-config --cluster-bucket mk-gcp-bucket --bucket-endpoint https://storage.googleapis.com --access-key XXXXXXXXXX --secret-key XXXXXXXXXXXX            
2017-10-26T17:19:37 INFO ax.cluster_management.argo_cluster_manager MainThread: Installing Argo platform ...
2017-10-26T17:19:37 INFO ax.cluster_management.argo_cluster_manager MainThread: s3 bucket endpoint: https://storage.googleapis.com
2017-10-26T17:19:37 INFO ax.meta.cluster_id MainThread: Instantiating cluster bucket ...
2017-10-26T17:19:44 INFO ax.cloud.aws.aws_s3 MainThread: Using region None for bucket mk-gcp-bucket
2017-10-26T17:19:45 INFO ax.meta.cluster_id MainThread: Cannot find cluster name/id mapping from bucket
2017-10-26T17:19:45 INFO ax.cluster_management.app.common MainThread: Cannot find cluster name id: Failed to load cluster name and cluster id from bucket. Cluster is not yet created.
2017-10-26T17:19:45 INFO ax.meta.cluster_id MainThread: Cluster id not provided, generate one.
2017-10-26T17:19:45 INFO ax.meta.cluster_id MainThread: Created new name-id cluster-1-dc7ac082-ba71-11e7-b4e1-025000000001
2017-10-26T17:19:45 INFO ax.meta.config_s3_path MainThread: Using AX cluster config path mk-gcp-bucket
2017-10-26T17:19:46 INFO ax.cloud.aws.aws_s3 MainThread: Using region None for bucket mk-gcp-bucket
2017-10-26T17:19:47 INFO ax.cloud.aws.aws_s3 MainThread: Using region None for bucket mk-gcp-bucket
2017-10-26T17:19:48 INFO ax.platform.ax_cluster_info MainThread: Downloading cluster current state ...
2017-10-26T17:19:48 INFO ax.platform.cluster_buckets MainThread: Creating and updating all cluster buckets ...
2017-10-26T17:19:50 INFO ax.cloud.aws.aws_s3 MainThread: Using region None for bucket mk-gcp-bucket
2017-10-26T17:19:50 INFO ax.cloud.aws.aws_s3 MainThread: Bucket mk-gcp-bucket already exist, don't create.
2017-10-26T17:19:50 INFO ax.platform.cluster_buckets MainThread: Created mk-gcp-bucket bucket ... DONE
2017-10-26T17:19:50 INFO ax.meta.config_s3_path MainThread: Using AX cluster data path mk-gcp-bucket
2017-10-26T17:19:52 INFO ax.cloud.aws.aws_s3 MainThread: Using region None for bucket mk-gcp-bucket
2017-10-26T17:19:52 INFO ax.cloud.aws.aws_s3 MainThread: Bucket mk-gcp-bucket already exist, don't create.
2017-10-26T17:19:52 INFO ax.platform.cluster_buckets MainThread: Created mk-gcp-bucket bucket ... DONE
2017-10-26T17:19:52 INFO ax.platform.cluster_buckets MainThread: Creating and updating all cluster buckets ... DONE
2017-10-26T17:19:52 INFO ax.platform.ax_cluster_info MainThread: Setting kube_config to /tmp/ax_kube/argo-gke-config
2017-10-26T17:19:52 INFO ax.platform.cluster_config.cluster_config MainThread: Uploading cluster config to s3 at cluster-1/dc7ac082-ba71-11e7-b4e1-025000000001/cluster_config ...
2017-10-26T17:19:53 INFO ax.platform.cluster_config.cluster_config MainThread: Uploading cluster config to s3 ... DONE
2017-10-26T17:19:53 INFO ax.platform.ax_cluster_info MainThread: Saving kubeconfig to s3 ...
2017-10-26T17:19:54 INFO ax.platform.ax_cluster_info MainThread: Saved kubeconfig /tmp/ax_kube/argo-gke-config at mk-gcp-bucket/cluster-1/dc7ac082-ba71-11e7-b4e1-025000000001/kube_config
2017-10-26T17:19:54 INFO ax.cluster_management.app.cluster_installer MainThread: Starting platform install
2017-10-26T17:19:54 INFO ax.platform.platform MainThread: Using Kubernetes manifest from /ax/config/service/argo-gke
2017-10-26T17:19:54 INFO ax.platform.platform MainThread: Using platform configuration "Argo Platform Config Only" from /ax/config/service/config/argo-wfe-platform-bootstrap.cfg
2017-10-26T17:19:54 ERROR ax.cluster_management.argo_cluster_manager MainThread: An error occurred (AccessDenied) when calling the AssumeRole operation: Not authorized to perform sts:AssumeRole
Traceback (most recent call last):
  File "/ax/python/ax/cluster_management/argo_cluster_manager.py", line 86, in parse_args_and_run
    getattr(self, cmd)(args)
  File "/ax/python/ax/cluster_management/argo_cluster_manager.py", line 267, in install_argo_only
    PlatformOnlyInstaller(platform_install_config).run()
  File "/ax/python/ax/cluster_management/app/cluster_installer.py", line 527, in run
    cluster_dns, username, password = self._ci_installer.install_and_run_platform()
  File "/ax/python/ax/cluster_management/app/cluster_installer.py", line 265, in install_and_run_platform
    config_file=self._cfg.bootstrap_config
  File "/ax/python/ax/platform/platform.py", line 93, in __init__
    self._account = AWSAccountInfo(aws_profile=self._aws_profile).get_account_id()
  File "/ax/python/ax/aws/profiles.py", line 23, in get_account_id
    sts = self._session.client("sts")
  File "/usr/local/lib/python2.7/dist-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python2.7/dist-packages/botocore/session.py", line 825, in create_client
    credentials = self.get_credentials()
  File "/usr/local/lib/python2.7/dist-packages/botocore/session.py", line 449, in get_credentials
    'credential_provider').load_credentials()
  File "/usr/local/lib/python2.7/dist-packages/botocore/credentials.py", line 1146, in load_credentials
    creds = provider.load()
  File "/usr/local/lib/python2.7/dist-packages/botocore/credentials.py", line 842, in load
    return self._load_creds_via_assume_role()
  File "/usr/local/lib/python2.7/dist-packages/botocore/credentials.py", line 861, in _load_creds_via_assume_role
    creds, response = self._retrieve_temp_credentials()
  File "/usr/local/lib/python2.7/dist-packages/botocore/credentials.py", line 970, in _retrieve_temp_credentials
    response = client.assume_role(**assume_role_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 312, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 601, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (AccessDenied) when calling the AssumeRole operation: Not authorized to perform sts:AssumeRole
```

 !!! Operation failed due to runtime error: An error occurred (AccessDenied) when calling the AssumeRole operation: Not authorized to perform sts:AssumeRole

**Comment by francis-ax** [comment]
talk to @mukulikak and she use the old argo version.  same command should work with new argo version..

**Comment by mukulikak** [comment]
happens with new image too

Getting the most up to date docker image (docker.applatix.net/axsys/axclustermanager:1.1.0-ba659e5) for cluster management...
1.1.0-ba659e5: Pulling from axsys/axclustermanager
Digest: sha256:257d4187d26740962ed164124ec60ced2c6a320666bb631ddff8d61c95dc6553
Status: Downloaded newer image for docker.applatix.net/axsys/axclustermanager:1.1.0-ba659e5

**Comment by mukulikak** [comment]
The fix worked.

**Comment by jessesuen** [comment]
Fixed.
