### ISSUE TITLE
claudia failed to launch from argo running on existing kubernetes

### ISSUE THREAD

**Issue by francis-ax** [argoproj/argo#414]
claudia failed to launch from argo running on existing kubernetes.

![image](https://user-images.githubusercontent.com/29876185/32230301-cad6f4c0-be8d-11e7-9eec-6ce06dc1aa1c.png)

```
2017-10-31T14:49:09 INFO ax.cloud.aws.ebs DummyThread-410: Creating EBS volume: Raw EBS Volume:: AX volume_id bf927836-1c35-462a-b146-be0b97794cf1, resource_id None, size: 20, type: gp2, zone: us-west-2c, misc: {'axrn': u'vol:/anonymous/application:claudia/deployment:claudia-costdb/costdb-vol'}
2017-10-31T14:49:39 ERROR AXmon DummyThread-410: Internal error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/ax/python/ax/platform/rest.py", line 589, in volume_create
    resource_id = manager.create_raw_volume(volume_id, volume_options)
  File "/ax/python/ax/platform/volumes.py", line 782, in create_raw_volume
    return raw_volume.create(vol_opts)
  File "/ax/python/ax/cloud/aws/ebs.py", line 143, in create
    response = _create_ebs_volume()
  File "/usr/lib/python2.7/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/lib/python2.7/site-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/lib/python2.7/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/lib/python2.7/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/ax/python/ax/cloud/aws/ebs.py", line 136, in _create_ebs_volume
    VolumeType=self.type)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 599, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (UnauthorizedOperation) when calling the CreateVolume operation: You are not authorized to perform this operation. Encoded authorization failure message: Nj1JHpxHVxC1Bll1GGYUKlChRbJ-5WLKXYxGDGSGjNpJHGy5xOuJJ7Qsi48WH6qYSymuxDMUOpUQQOWRYPc5umgPYlpQ-q67a9soaS5ufMeuB593W6LU3vM5P2znv5dHB_3zUGGVxKeJ47qrX4FvIBzGLapOkrzwAfztLKhmGtl6M03dq30PGsxQkoljTkxrQ5CGr2LlPMqVk_aP7KqIrahrK_3g-HQyVRPtUCkWwykb_BI9II9O2f5MCKn8CgX8yVhUXkKB0rFFcTAyKMyBmtNllLV9pdArQmNK7TfsqpAQfiq33lsCinZSNkWs-amiWXeIhCrLVmVTtmiw-S7ji3p_RrN26l_ejXbscl9LNs5VdGDtXsSGuh7-UNEr65p972gl0rERkeLPdnIZ3aiJHGKJC2cTZL56gIw_RJ--_ICxZRJiaPp7uHsSYFoxQY4x4mvUWVstyTQMeazF-NonW13u0SYbxHx3RYp0P6K4cTFFPM5vHGuFiv7Z_5sAJZfI3DRNGPbQjyePrLIw79SC2Y_MzVH8i3QzjC1ZCtGjSBcdoaZokJIoefhVBo8K2i1oLKdrbgJi7UJGzytK98EwGgT2lmWJalmADQsdQQRA1N9W8cuPMbL3xz_0emQBDkxiI7dx
::ffff:100.96.2.211 - - [2017-10-31 14:49:39] "POST /v1/axmon/volume/bf927836-1c35-462a-b146-be0b97794cf1 HTTP/1.1" 400 3502 30.266777
```

**Comment by francis-ax** [comment]
double check the kubernete minion node IAM policy and found out that policy is being restored to the default one. Not sure how this happens. 

The claudia is working again after I apply the correct policy. Close the bug.
