### ISSUE TITLE
Argo UI - Archived Workflows - Error when clicking on hidden nodes ellipsis

### ISSUE THREAD

**Issue by adityasundaramurthy-maersk** [argoproj/argo#4236]
## Summary 

What happened/what you expected to happen?

When trying to view the hidden nodes in an archived workflow by clicking on the ellipsis, the following error occurs.

<img width="1363" alt="Screenshot 2020-10-08 at 10 15 57" src="https://user-images.githubusercontent.com/70176055/95433288-09b7b480-0950-11eb-8489-9cc260b63f0e.png">

<img width="864" alt="Screenshot 2020-10-08 at 10 16 26" src="https://user-images.githubusercontent.com/70176055/95433309-0fad9580-0950-11eb-8dd2-8f87bba7d5fd.png">

## Diagnostics

What Kubernetes provider are you using? 
> Azure Kubernetes Service

What version of Argo Workflows are you running? 
> Argo v2.11.1

Occurs for all workflows that have multiple parallel steps generated with `withParam`

Logs from Argo UI:
```
 Cannot read property 'inputs' of undefined
 Reload this page to try again.

Stack Trace
TypeError: Cannot read property 'inputs' of undefined
    at t.WorkflowNodeInfo (https://argo-platform.maersk-digital.net/main.2abc14257d733f566d49.js:478:515762)
    at Zo (https://argo-platform.maersk-digital.net/main.2abc14257d733f566d49.js:396:52993)
    at Di (https://argo-platform.maersk-digital.net/main.2abc14257d733f566d49.js:396:59761)
    at Pi (https://argo-platform.maersk-digital.net/main.2abc14257d733f566d49.js:396:66453)
    at Ua (https://argo-platform.maersk-digital.net/main.2abc14257d733f566d49.js:396:90552)
    at Xa (https://argo-platform.maersk-digital.net/main.2abc14257d733f566d49.js:396:90936)
    at Es (https://argo-platform.maersk-digital.net/main.2abc14257d733f566d49.js:396:97823)
    at Ds (https://argo-platform.maersk-digital.net/main.2abc14257d733f566d49.js:396:97203)
    at js (https://argo-platform.maersk-digital.net/main.2abc14257d733f566d49.js:396:98578)
    at Cn (https://argo-platform.maersk-digital.net/main.2abc14257d733f566d49.js:396:30569)
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Can I please request the full workflow YAML so I can verify my fix works?

**Comment by alexec** [comment]
Reproduces using loops-param-result- example.
