### ISSUE TITLE
 argo-only installation failed on GKE kubernetes version 1.8.x

### ISSUE THREAD

**Issue by francis-ax** [argoproj/argo#447]
argo-only installation failed on GKE kubernetes version 1.8.x , please see following logs.
The same istallation works okay for kubernetes version 1.7.x

```
2017-11-14T11:27:43 INFO ax.cluster_management.argo_cluster_manager MainThread: Installing Argo platform ...
2017-11-14T11:27:43 INFO ax.cluster_management.argo_cluster_manager MainThread: s3 bucket endpoint: https://storage.googleapis.com
2017-11-14T11:27:43 INFO ax.meta.cluster_id MainThread: Instantiating cluster bucket ...
2017-11-14T11:27:50 INFO ax.cloud.aws.aws_s3 MainThread: Using region None for bucket ax-francis
2017-11-14T11:27:52 INFO ax.meta.cluster_id MainThread: Cannot find cluster name/id mapping from bucket
2017-11-14T11:27:52 INFO ax.cluster_management.app.common MainThread: Cannot find cluster name id: Failed to load cluster name and cluster id from bucket. Cluster is not yet created.
2017-11-14T11:27:52 INFO ax.meta.cluster_id MainThread: Cluster id not provided, generate one.
2017-11-14T11:27:52 INFO ax.meta.cluster_id MainThread: Created new name-id francis-gke181-02-da462fa6-c92e-11e7-a3a1-025000000001
2017-11-14T11:27:52 INFO ax.meta.config_s3_path MainThread: Using AX cluster config path ax-francis
2017-11-14T11:27:54 INFO ax.cloud.aws.aws_s3 MainThread: Using region None for bucket ax-francis
2017-11-14T11:27:57 INFO ax.cloud.aws.aws_s3 MainThread: Using region None for bucket ax-francis
2017-11-14T11:27:57 INFO ax.platform.ax_cluster_info MainThread: Downloading cluster current state ...
2017-11-14T11:27:58 INFO ax.platform.cluster_buckets MainThread: Creating and updating all cluster buckets ...
2017-11-14T11:28:00 INFO ax.cloud.aws.aws_s3 MainThread: Using region None for bucket ax-francis
2017-11-14T11:28:00 INFO ax.cloud.aws.aws_s3 MainThread: Bucket ax-francis already exist, don't create.
2017-11-14T11:28:00 INFO ax.platform.cluster_buckets MainThread: Created ax-francis bucket ... DONE
2017-11-14T11:28:00 INFO ax.meta.config_s3_path MainThread: Using AX cluster data path ax-francis
2017-11-14T11:28:03 INFO ax.cloud.aws.aws_s3 MainThread: Using region None for bucket ax-francis
2017-11-14T11:28:04 INFO ax.cloud.aws.aws_s3 MainThread: Bucket ax-francis already exist, don't create.
2017-11-14T11:28:04 INFO ax.platform.cluster_buckets MainThread: Created ax-francis bucket ... DONE
2017-11-14T11:28:04 INFO ax.platform.cluster_buckets MainThread: Creating and updating all cluster buckets ... DONE
2017-11-14T11:28:04 INFO ax.platform.ax_cluster_info MainThread: Setting kube_config to /tmp/ax_kube/cluster_francis-gke181-02.conf
2017-11-14T11:28:04 INFO ax.platform.cluster_config.cluster_config MainThread: Uploading cluster config to s3 at francis-gke181-02/da462fa6-c92e-11e7-a3a1-025000000001/cluster_config ...
2017-11-14T11:28:05 INFO ax.platform.cluster_config.cluster_config MainThread: Uploading cluster config to s3 ... DONE
2017-11-14T11:28:05 INFO ax.platform.ax_cluster_info MainThread: Saving kubeconfig to s3 ...
2017-11-14T11:28:06 INFO ax.platform.ax_cluster_info MainThread: Saved kubeconfig /tmp/ax_kube/cluster_francis-gke181-02.conf at ax-francis/francis-gke181-02/da462fa6-c92e-11e7-a3a1-025000000001/kube_config
2017-11-14T11:28:06 INFO ax.cluster_management.app.cluster_installer MainThread: Starting platform install
2017-11-14T11:28:06 INFO ax.platform.platform MainThread: Using Kubernetes manifest from /ax/config/service/argo-gke
2017-11-14T11:28:06 INFO ax.platform.platform MainThread: Using platform configuration "Argo Platform Config Only" from /ax/config/service/config/argo-wfe-platform-bootstrap.cfg
2017-11-14T11:28:06 INFO ax.cloud.aws.aws_s3 MainThread: Using region None for bucket ax-francis
2017-11-14T11:28:06 INFO ax.platform.ax_monitor_helper kube-events-monitor: Thread kube-events-monitor: Starts
2017-11-14T11:28:06 INFO ax.platform.ax_monitor_helper kube-pods-monitor: Thread kube-pods-monitor: Starts
2017-11-14T11:28:06 INFO ax.platform.ax_monitor_helper kube-persistentvolumeclaims-monitor: Thread kube-persistentvolumeclaims-monitor: Starts
2017-11-14T11:28:06 INFO ax.platform.ax_monitor_helper kube-persistentvolumes-monitor: Thread kube-persistentvolumes-monitor: Starts
2017-11-14T11:28:06 INFO ax.platform.ax_monitor_helper kube-services-monitor: Thread kube-services-monitor: Starts
2017-11-14T11:28:06 INFO ax.platform.cluster_config.cluster_config MainThread: Uploading cluster config to s3 at francis-gke181-02/da462fa6-c92e-11e7-a3a1-025000000001/cluster_config ...
2017-11-14T11:28:06 ERROR ax.platform.ax_monitor_helper kube-events-monitor: Thread kube-events-monitor: got exception 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/namespaces/axsys/events
Traceback (most recent call last):
  File "/ax/python/ax/platform/ax_monitor_helper.py", line 75, in run
    for obj in objs:
  File "/ax/python/ax/kubernetes/client.py", line 533, in _stream_helper
    raise AXKubeApiException(str(e))
AXKubeApiException: 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/namespaces/axsys/events
2017-11-14T11:28:06 ERROR ax.platform.ax_monitor_helper kube-persistentvolumeclaims-monitor: Thread kube-persistentvolumeclaims-monitor: got exception 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/namespaces/axsys/persistentvolumeclaims
Traceback (most recent call last):
  File "/ax/python/ax/platform/ax_monitor_helper.py", line 75, in run
    for obj in objs:
  File "/ax/python/ax/kubernetes/client.py", line 533, in _stream_helper
    raise AXKubeApiException(str(e))
AXKubeApiException: 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/namespaces/axsys/persistentvolumeclaims
2017-11-14T11:28:06 ERROR ax.platform.ax_monitor_helper kube-persistentvolumes-monitor: Thread kube-persistentvolumes-monitor: got exception 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/persistentvolumes
Traceback (most recent call last):
  File "/ax/python/ax/platform/ax_monitor_helper.py", line 75, in run
    for obj in objs:
  File "/ax/python/ax/kubernetes/client.py", line 533, in _stream_helper
    raise AXKubeApiException(str(e))
AXKubeApiException: 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/persistentvolumes
2017-11-14T11:28:06 ERROR ax.platform.ax_monitor_helper kube-pods-monitor: Thread kube-pods-monitor: got exception 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/namespaces/axsys/pods
Traceback (most recent call last):
  File "/ax/python/ax/platform/ax_monitor_helper.py", line 75, in run
    for obj in objs:
  File "/ax/python/ax/kubernetes/client.py", line 533, in _stream_helper
    raise AXKubeApiException(str(e))
AXKubeApiException: 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/namespaces/axsys/pods
2017-11-14T11:28:06 ERROR ax.platform.ax_monitor_helper kube-services-monitor: Thread kube-services-monitor: got exception 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/namespaces/axsys/services
Traceback (most recent call last):
  File "/ax/python/ax/platform/ax_monitor_helper.py", line 75, in run
    for obj in objs:
  File "/ax/python/ax/kubernetes/client.py", line 533, in _stream_helper
    raise AXKubeApiException(str(e))
AXKubeApiException: 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/namespaces/axsys/services
2017-11-14T11:28:07 INFO ax.platform.cluster_config.cluster_config MainThread: Uploading cluster config to s3 ... DONE
2017-11-14T11:28:07 DEBUG ax.platform.platform MainThread: Replacing ENVs: {'AX_CLUSTER_INSTALL_VERSION': '1.1.0-dacad13-3cc9795', 'SANDBOX_ENABLED': 'None', 'ARGO_S3_ACCESS_KEY_ID': 'R09PR1lSWlBCQ1RTTzJDN1Y3Skk=', 'AX_AWS_ACCOUNT': '', 'AX_CUSTOMER_ID': 'user-customer-id', 'NEW_KUBE_SALT_SHA1': ' ', 'ARGO_DATA_BUCKET_NAME': 'ax-francis', 'AX_KUBE_VERSION': '1.6.7', 'NAMESPACE': 'axsys', 'LOAD_BALANCER_TYPE': 'LoadBalancer', 'NEW_KUBE_SERVER_SHA1': ' ', 'ARGO_S3_ACCESS_KEY_SECRET': 'UFZhTXRPTzlNUzVUZjhDSlcrVjAwdE1BTGlpaWpmNzhQWnZHb0FCMg==', 'DNS_SERVER_IP': '192.168.0.10', 'VERSION': '1.1.0-45da485', 'AX_CLUSTER_META_URL_V1': 'https://s3-None.amazonaws.com/ax-francis/francis-gke181-02/da462fa6-c92e-11e7-a3a1-025000000001/metadata/v1/metadata.yaml', 'REGISTRY': 'docker.applatix.net', 'TRUSTED_CIDR': '["0.0.0.0/0"]', 'REGISTRY_SECRETS': 'ewoJImF1dGhzIjogewoJCSJkb2NrZXIuYXBwbGF0aXgubmV0IjogewoJCQkiYXV0aCI6ICJZWGhrWlhZNk5HeDZiek5NY1haamJWUjMiCgkJfQoJfQp9Cg==', 'AX_CLUSTER_NAME_ID': 'francis-gke181-02-da462fa6-c92e-11e7-a3a1-025000000001', 'ARGO_LOG_BUCKET_NAME': 'ax-francis', 'AX_AWS_REGION': 'None'}
2017-11-14T11:28:07 INFO ax.platform.platform MainThread: Create step: Essential Kubernetes Namespaces
2017-11-14T11:28:07 INFO ax.platform.platform MainThread: Creating platform objects


NAME                      |  MANIFEST                                                                                                       |  NAMESPACE
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
axuser-namespace          |  /ax/config/service/argo-gke/axuser-namespace.yml.in                                                            |  None
axsys-namespace           |  /ax/config/service/argo-gke/axsys-namespace.yml.in                                                             |  None

2017-11-14T11:28:09 INFO ax.platform.platform Thread-7: Creating axuser-namespace in namespace None ...
2017-11-14T11:28:12 INFO ax.platform.platform Thread-8: Creating axsys-namespace in namespace None ...
2017-11-14T11:28:16 ERROR ax.util.kube_poll Thread-1: Unable to call kube api with error (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Date': 'Tue, 14 Nov 2017 11:28:16 GMT', 'Content-Length': '317', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces is forbidden: User \"system:serviceaccount:default:default\" cannot list namespaces at the cluster scope: Unknown user \"system:serviceaccount:default:default\"","reason":"Forbidden","details":{"kind":"namespaces"},"code":403}


2017-11-14T11:28:17 ERROR ax.platform.ax_monitor_helper kube-persistentvolumeclaims-monitor: Thread kube-persistentvolumeclaims-monitor: got exception 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/namespaces/axsys/persistentvolumeclaims
Traceback (most recent call last):
  File "/ax/python/ax/platform/ax_monitor_helper.py", line 75, in run
    for obj in objs:
  File "/ax/python/ax/kubernetes/client.py", line 533, in _stream_helper
    raise AXKubeApiException(str(e))
AXKubeApiException: 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/namespaces/axsys/persistentvolumeclaims
2017-11-14T11:28:17 ERROR ax.platform.ax_monitor_helper kube-pods-monitor: Thread kube-pods-monitor: got exception 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/namespaces/axsys/pods
Traceback (most recent call last):
  File "/ax/python/ax/platform/ax_monitor_helper.py", line 75, in run
    for obj in objs:
  File "/ax/python/ax/kubernetes/client.py", line 533, in _stream_helper
    raise AXKubeApiException(str(e))
AXKubeApiException: 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/namespaces/axsys/pods
2017-11-14T11:28:17 ERROR ax.platform.ax_monitor_helper kube-events-monitor: Thread kube-events-monitor: got exception 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/namespaces/axsys/events
Traceback (most recent call last):
  File "/ax/python/ax/platform/ax_monitor_helper.py", line 75, in run
    for obj in objs:
  File "/ax/python/ax/kubernetes/client.py", line 533, in _stream_helper
    raise AXKubeApiException(str(e))
AXKubeApiException: 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/namespaces/axsys/events
2017-11-14T11:28:17 ERROR ax.platform.ax_monitor_helper kube-persistentvolumes-monitor: Thread kube-persistentvolumes-monitor: got exception 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/persistentvolumes
Traceback (most recent call last):
  File "/ax/python/ax/platform/ax_monitor_helper.py", line 75, in run
    for obj in objs:
  File "/ax/python/ax/kubernetes/client.py", line 533, in _stream_helper
    raise AXKubeApiException(str(e))
AXKubeApiException: 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/persistentvolumes
2017-11-14T11:28:17 ERROR ax.platform.ax_monitor_helper kube-services-monitor: Thread kube-services-monitor: got exception 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/namespaces/axsys/services
Traceback (most recent call last):
  File "/ax/python/ax/platform/ax_monitor_helper.py", line 75, in run
    for obj in objs:
  File "/ax/python/ax/kubernetes/client.py", line 533, in _stream_helper
    raise AXKubeApiException(str(e))
AXKubeApiException: 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/namespaces/axsys/services
2017-11-14T11:28:23 ERROR ax.util.kube_poll Thread-1: Unable to call kube api with error (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Date': 'Tue, 14 Nov 2017 11:28:22 GMT', 'Content-Length': '317', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces is forbidden: User \"system:serviceaccount:default:default\" cannot list namespaces at the cluster scope: Unknown user \"system:serviceaccount:default:default\"","reason":"Forbidden","details":{"kind":"namespaces"},"code":403}


2017-11-14T11:28:28 ERROR ax.platform.ax_monitor_helper kube-persistentvolumes-monitor: Thread kube-persistentvolumes-monitor: got exception 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/persistentvolumes
Traceback (most recent call last):
  File "/ax/python/ax/platform/ax_monitor_helper.py", line 75, in run
    for obj in objs:
  File "/ax/python/ax/kubernetes/client.py", line 533, in _stream_helper
    raise AXKubeApiException(str(e))
AXKubeApiException: 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/persistentvolumes
2017-11-14T11:28:28 ERROR ax.platform.ax_monitor_helper kube-events-monitor: Thread kube-events-monitor: got exception 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/namespaces/axsys/events
Traceback (most recent call last):
  File "/ax/python/ax/platform/ax_monitor_helper.py", line 75, in run
    for obj in objs:
  File "/ax/python/ax/kubernetes/client.py", line 533, in _stream_helper
    raise AXKubeApiException(str(e))
AXKubeApiException: 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/namespaces/axsys/events
2017-11-14T11:28:28 ERROR ax.platform.ax_monitor_helper kube-persistentvolumeclaims-monitor: Thread kube-persistentvolumeclaims-monitor: got exception 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/namespaces/axsys/persistentvolumeclaims
Traceback (most recent call last):
  File "/ax/python/ax/platform/ax_monitor_helper.py", line 75, in run
    for obj in objs:
  File "/ax/python/ax/kubernetes/client.py", line 533, in _stream_helper
    raise AXKubeApiException(str(e))
AXKubeApiException: 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/namespaces/axsys/persistentvolumeclaims
2017-11-14T11:28:28 ERROR ax.platform.ax_monitor_helper kube-pods-monitor: Thread kube-pods-monitor: got exception 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/namespaces/axsys/pods
Traceback (most recent call last):
  File "/ax/python/ax/platform/ax_monitor_helper.py", line 75, in run
    for obj in objs:
  File "/ax/python/ax/kubernetes/client.py", line 533, in _stream_helper
    raise AXKubeApiException(str(e))
AXKubeApiException: 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/namespaces/axsys/pods
2017-11-14T11:28:28 ERROR ax.platform.ax_monitor_helper kube-services-monitor: Thread kube-services-monitor: got exception 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/namespaces/axsys/services
Traceback (most recent call last):
  File "/ax/python/ax/platform/ax_monitor_helper.py", line 75, in run
    for obj in objs:
  File "/ax/python/ax/kubernetes/client.py", line 533, in _stream_helper
    raise AXKubeApiException(str(e))
AXKubeApiException: 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/namespaces/axsys/services
2017-11-14T11:28:29 ERROR ax.util.kube_poll Thread-1: Unable to call kube api with error (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Date': 'Tue, 14 Nov 2017 11:28:29 GMT', 'Content-Length': '317', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces is forbidden: User \"system:serviceaccount:default:default\" cannot list namespaces at the cluster scope: Unknown user \"system:serviceaccount:default:default\"","reason":"Forbidden","details":{"kind":"namespaces"},"code":403}


2017-11-14T11:28:35 ERROR ax.util.kube_poll Thread-1: Unable to call kube api with error (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Date': 'Tue, 14 Nov 2017 11:28:35 GMT', 'Content-Length': '317', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces is forbidden: User \"system:serviceaccount:default:default\" cannot list namespaces at the cluster scope: Unknown user \"system:serviceaccount:default:default\"","reason":"Forbidden","details":{"kind":"namespaces"},"code":403}


2017-11-14T11:28:38 ERROR ax.platform.ax_monitor_helper kube-persistentvolumes-monitor: Thread kube-persistentvolumes-monitor: got exception 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/persistentvolumes
Traceback (most recent call last):
  File "/ax/python/ax/platform/ax_monitor_helper.py", line 75, in run
    for obj in objs:
  File "/ax/python/ax/kubernetes/client.py", line 533, in _stream_helper
    raise AXKubeApiException(str(e))
AXKubeApiException: 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/persistentvolumes
2017-11-14T11:28:38 ERROR ax.platform.ax_monitor_helper kube-events-monitor: Thread kube-events-monitor: got exception 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/namespaces/axsys/events
Traceback (most recent call last):
  File "/ax/python/ax/platform/ax_monitor_helper.py", line 75, in run
    for obj in objs:
  File "/ax/python/ax/kubernetes/client.py", line 533, in _stream_helper
    raise AXKubeApiException(str(e))
AXKubeApiException: 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/namespaces/axsys/events
2017-11-14T11:28:38 ERROR ax.platform.ax_monitor_helper kube-pods-monitor: Thread kube-pods-monitor: got exception 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/namespaces/axsys/pods
Traceback (most recent call last):
  File "/ax/python/ax/platform/ax_monitor_helper.py", line 75, in run
    for obj in objs:
  File "/ax/python/ax/kubernetes/client.py", line 533, in _stream_helper
    raise AXKubeApiException(str(e))
AXKubeApiException: 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/namespaces/axsys/pods
2017-11-14T11:28:38 ERROR ax.platform.ax_monitor_helper kube-services-monitor: Thread kube-services-monitor: got exception 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/namespaces/axsys/services
Traceback (most recent call last):
  File "/ax/python/ax/platform/ax_monitor_helper.py", line 75, in run
    for obj in objs:
  File "/ax/python/ax/kubernetes/client.py", line 533, in _stream_helper
    raise AXKubeApiException(str(e))
AXKubeApiException: 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/namespaces/axsys/services
2017-11-14T11:28:38 ERROR ax.platform.ax_monitor_helper kube-persistentvolumeclaims-monitor: Thread kube-persistentvolumeclaims-monitor: got exception 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/namespaces/axsys/persistentvolumeclaims
Traceback (most recent call last):
  File "/ax/python/ax/platform/ax_monitor_helper.py", line 75, in run
    for obj in objs:
  File "/ax/python/ax/kubernetes/client.py", line 533, in _stream_helper
    raise AXKubeApiException(str(e))
AXKubeApiException: 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/namespaces/axsys/persistentvolumeclaims
2017-11-14T11:28:42 ERROR ax.util.kube_poll Thread-1: Unable to call kube api with error (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Date': 'Tue, 14 Nov 2017 11:28:42 GMT', 'Content-Length': '317', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces is forbidden: User \"system:serviceaccount:default:default\" cannot list namespaces at the cluster scope: Unknown user \"system:serviceaccount:default:default\"","reason":"Forbidden","details":{"kind":"namespaces"},"code":403}


2017-11-14T11:28:47 WARNING ax.kubernetes.kube_object Thread-7: Failed to create object /ax/config/service/argo-gke/axuser-namespace.yml.in due to Error from server (Forbidden): error when creating "/tmp/kube-obj-K1Kpas": namespaces is forbidden: User "system:serviceaccount:default:default" cannot create namespaces at the cluster scope: Unknown user "system:serviceaccount:default:default"

2017-11-14T11:28:48 ERROR ax.util.kube_poll Thread-1: Unable to call kube api with error (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Date': 'Tue, 14 Nov 2017 11:28:48 GMT', 'Content-Length': '317', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces is forbidden: User \"system:serviceaccount:default:default\" cannot list namespaces at the cluster scope: Unknown user \"system:serviceaccount:default:default\"","reason":"Forbidden","details":{"kind":"namespaces"},"code":403}


2017-11-14T11:28:49 ERROR ax.platform.ax_monitor_helper kube-services-monitor: Thread kube-services-monitor: got exception 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/namespaces/axsys/services
Traceback (most recent call last):
  File "/ax/python/ax/platform/ax_monitor_helper.py", line 75, in run
    for obj in objs:
  File "/ax/python/ax/kubernetes/client.py", line 533, in _stream_helper
    raise AXKubeApiException(str(e))
AXKubeApiException: 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/namespaces/axsys/services
2017-11-14T11:28:49 ERROR ax.platform.ax_monitor_helper kube-events-monitor: Thread kube-events-monitor: got exception 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/namespaces/axsys/events
Traceback (most recent call last):
  File "/ax/python/ax/platform/ax_monitor_helper.py", line 75, in run
    for obj in objs:
  File "/ax/python/ax/kubernetes/client.py", line 533, in _stream_helper
    raise AXKubeApiException(str(e))
AXKubeApiException: 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/namespaces/axsys/events
2017-11-14T11:28:49 ERROR ax.platform.ax_monitor_helper kube-pods-monitor: Thread kube-pods-monitor: got exception 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/namespaces/axsys/pods
Traceback (most recent call last):
  File "/ax/python/ax/platform/ax_monitor_helper.py", line 75, in run
    for obj in objs:
  File "/ax/python/ax/kubernetes/client.py", line 533, in _stream_helper
    raise AXKubeApiException(str(e))
AXKubeApiException: 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/namespaces/axsys/pods
2017-11-14T11:28:49 ERROR ax.platform.ax_monitor_helper kube-persistentvolumes-monitor: Thread kube-persistentvolumes-monitor: got exception 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/persistentvolumes
Traceback (most recent call last):
  File "/ax/python/ax/platform/ax_monitor_helper.py", line 75, in run
    for obj in objs:
  File "/ax/python/ax/kubernetes/client.py", line 533, in _stream_helper
    raise AXKubeApiException(str(e))
AXKubeApiException: 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/persistentvolumes
2017-11-14T11:28:49 ERROR ax.platform.ax_monitor_helper kube-persistentvolumeclaims-monitor: Thread kube-persistentvolumeclaims-monitor: got exception 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/namespaces/axsys/persistentvolumeclaims
Traceback (most recent call last):
  File "/ax/python/ax/platform/ax_monitor_helper.py", line 75, in run
    for obj in objs:
  File "/ax/python/ax/kubernetes/client.py", line 533, in _stream_helper
    raise AXKubeApiException(str(e))
AXKubeApiException: 403 Client Error: Forbidden for url: https://35.197.84.10:443/api/v1/watch/namespaces/axsys/persistentvolumeclaims
2017-11-14T11:28:49 WARNING ax.kubernetes.kube_object Thread-8: Failed to create object /ax/config/service/argo-gke/axsys-namespace.yml.in due to Error from server (Forbidden): error when creating "/tmp/kube-obj-8lJz0Y": namespaces is forbidden: User "system:serviceaccount:default:default" cannot create namespaces at the cluster scope: Unknown user "system:serviceaccount:default:default"

2017-11-14T11:28:49 ERROR ax.platform.platform MainThread: Un-recognized error during create: Error from server (Forbidden): error when creating "/tmp/kube-obj-K1Kpas": namespaces is forbidden: User "system:serviceaccount:default:default" cannot create namespaces at the cluster scope: Unknown user "system:serviceaccount:default:default"
Traceback (most recent call last):
  File "/ax/python/ax/platform/platform.py", line 750, in _generate_report
    result = results[name].get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
AXPlatformException: Un-recognized error during create: Error from server (Forbidden): error when creating "/tmp/kube-obj-K1Kpas": namespaces is forbidden: User "system:serviceaccount:default:default" cannot create namespaces at the cluster scope: Unknown user "system:serviceaccount:default:default"

2017-11-14T11:28:49 ERROR ax.platform.platform MainThread: Un-recognized error during create: Error from server (Forbidden): error when creating "/tmp/kube-obj-8lJz0Y": namespaces is forbidden: User "system:serviceaccount:default:default" cannot create namespaces at the cluster scope: Unknown user "system:serviceaccount:default:default"
Traceback (most recent call last):
  File "/ax/python/ax/platform/platform.py", line 750, in _generate_report
    result = results[name].get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
AXPlatformException: Un-recognized error during create: Error from server (Forbidden): error when creating "/tmp/kube-obj-8lJz0Y": namespaces is forbidden: User "system:serviceaccount:default:default" cannot create namespaces at the cluster scope: Unknown user "system:serviceaccount:default:default"

2017-11-14T11:28:49 INFO ax.platform.platform MainThread:

Platform Create FAILED. Report:

NAME                      |  STATUS                                                                                                         |  TIME (sec)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
axuser-namespace          |  EXCEPTION                                                                                                      |  UNKNOWN
axsys-namespace           |  EXCEPTION                                                                                                      |  UNKNOWN

======= WARNING EVENTS =======
axuser-namespace: Un-recognized error during create: Error from server (Forbidden): error when creating "/tmp/kube-obj-K1Kpas": namespaces is forbidden: User "system:serviceaccount:default:default" cannot create namespaces at the cluster scope: Unknown user "system:serviceaccount:default:default"


axsys-namespace: Un-recognized error during create: Error from server (Forbidden): error when creating "/tmp/kube-obj-8lJz0Y": namespaces is forbidden: User "system:serviceaccount:default:default" cannot create namespaces at the cluster scope: Unknown user "system:serviceaccount:default:default"


==============================

2017-11-14T11:28:49 ERROR ax.cluster_management.app.cluster_installer MainThread: Failed to create platform objects.
Traceback (most recent call last):
  File "/ax/python/ax/cluster_management/app/cluster_installer.py", line 271, in install_and_run_platform
    platform.start()
  File "/ax/python/ax/platform/platform.py", line 313, in start
    self.create_objects(steps[0])
  File "/ax/python/ax/platform/platform.py", line 404, in create_objects
    raise AXPlatformException("Failed to create platform objects.")
AXPlatformException: Failed to create platform objects.
2017-11-14T11:28:49 ERROR ax.cluster_management.argo_cluster_manager MainThread: Failed to create platform objects.
Please manually check the cluster status and retry installation with same command if the error is transient.
Traceback (most recent call last):
  File "/ax/python/ax/cluster_management/argo_cluster_manager.py", line 86, in parse_args_and_run
    getattr(self, cmd)(args)
  File "/ax/python/ax/cluster_management/argo_cluster_manager.py", line 267, in install_argo_only
    PlatformOnlyInstaller(platform_install_config).run()
  File "/ax/python/ax/cluster_management/app/cluster_installer.py", line 527, in run
    cluster_dns, username, password = self._ci_installer.install_and_run_platform()
  File "/ax/python/ax/cluster_management/app/cluster_installer.py", line 279, in install_and_run_platform
    raise RuntimeError(install_platform_failure_message)
RuntimeError: Failed to create platform objects.
Please manually check the cluster status and retry installation with same command if the error is transient.

 !!! Operation failed due to runtime error: Failed to create platform objects.
Please manually check the cluster status and retry installation with same command if the error is transient.

```

**Comment by edlee2121** [comment]
@francis-ax This is installing Argo 1.1?

**Comment by francis-ax** [comment]
yes this is for Argo 1.1
