### ISSUE TITLE
script with an input artifact crashes workflow controller

### ISSUE THREAD

**Issue by mthx** [argoproj/argo#617]
I tried using a `script` with an input artifact and this seems to crash the workflow controller.  I'm not sure whether this is intended to be supported (though it would be useful), but if not it would be better to validate it and reject or at least fail the workflow.  I was using v2.0.0-alpha2.

See the workflow in [crash.txt](https://github.com/argoproj/argo/files/1572430/crash.txt).  `consumeArtifactWithoutScript` passes, `consumeArtifactWithScript` doesn't properly start, resulting in odd `argo get` output and the following in the `workflow-controller`'s logs:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc0 pc=0xf018f8]

goroutine 24 [running]:
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).addInputArtifactsVolumes(0xc4207320c0, 0xc4207e9500, 0xc4208069c0, 0x0, 0x0)
	/root/go/src/github.com/argoproj/argo/workflow/controller/workflowpod.go:358 +0x2f8
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).createWorkflowPod(0xc4207320c0, 0xc4202ce4b0, 0x28, 0xc4208068f0, 0x5, 0xc420164970)
	/root/go/src/github.com/argoproj/argo/workflow/controller/workflowpod.go:179 +0x879
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeScript(0xc4207320c0, 0xc4202ce4b0, 0x28, 0xc4208068f0, 0xc42045de00, 0x1)
	/root/go/src/github.com/argoproj/argo/workflow/controller/operator.go:663 +0x56
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeTemplate(0xc4207320c0, 0xc42019d580, 0x19, 0x0, 0x0, 0x0, 0xc42045de00, 0x1, 0x4, 0xc4202ce4b0, ...)
	/root/go/src/github.com/argoproj/argo/workflow/controller/operator.go:261 +0x7ce
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeStepGroup(0xc4207320c0, 0xc420417680, 0x1, 0x4, 0xc420164840, 0xe, 0xc4208e0d90, 0x0, 0x0)
	/root/go/src/github.com/argoproj/argo/workflow/controller/operator.go:471 +0x79e
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeSteps(0xc4207320c0, 0xc42025b160, 0xb, 0xc420806680, 0x0, 0x0)
	/root/go/src/github.com/argoproj/argo/workflow/controller/operator.go:372 +0xcc4
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeTemplate(0xc4207320c0, 0xc42025b1b0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42025b160, ...)
	/root/go/src/github.com/argoproj/argo/workflow/controller/operator.go:254 +0x463
github.com/argoproj/argo/workflow/controller.(*WorkflowController).operateWorkflow(0xc4200a2750, 0xc4208f4000)
	/root/go/src/github.com/argoproj/argo/workflow/controller/operator.go:94 +0x55f
github.com/argoproj/argo/workflow/controller.(*WorkflowController).Run(0xc4200a2750, 0x187f640, 0xc420402680, 0xc42013bcf0, 0xc42007fef0)
	/root/go/src/github.com/argoproj/argo/workflow/controller/controller.go:141 +0x61d
created by main.Run
	/root/go/src/github.com/argoproj/argo/cmd/workflow-controller/main.go:89 +0x345
```

**Comment by jessesuen** [comment]
Script templates with input artifacts are intended to work, so this is a bug.

**Comment by jessesuen** [comment]
Two issues here:
1. the segfault itself
2. the control loop needs to recover() from the panic and probably mark the workflow failed and completed so it won't affect the controller ever again.
