### ISSUE TITLE
WorkflowController in crashloop because artifactInputs location collides with user specified volume

### ISSUE THREAD

**Issue by jlewi** [argoproj/argo#633]
My workflow controller pod is stuck in a crash loop with the following segmentation fault

```
time="2017-12-29T00:15:27Z" level=info msg="Processing wf: /apis/argoproj.io/v1alpha1/namespaces/kubeflow-test-infra/workflows/e2e-test-presubmit-20171228-154513"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc0 pc=0xf018f8]

goroutine 51 [running]:
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).addInputArtifactsVolumes(0xc420422c60, 0xc4200a4000, 0xc42043aa90, 0x0, 0x0)
	/root/go/src/github.com/argoproj/argo/workflow/controller/workflowpod.go:358 +0x2f8
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).createWorkflowPod(0xc420422c60, 0xc42018cb70, 0x2e, 0xc42043a9c0, 0x15, 0xc420382980)
	/root/go/src/github.com/argoproj/argo/workflow/controller/workflowpod.go:179 +0x879
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeScript(0xc420422c60, 0xc42018cb70, 0x2e, 0xc42043a9c0, 0x0, 0x0)
	/root/go/src/github.com/argoproj/argo/workflow/controller/operator.go:663 +0x56
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeTemplate(0xc420422c60, 0xc420318180, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42018cb70, ...)
	/root/go/src/github.com/argoproj/argo/workflow/controller/operator.go:261 +0x7ce
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeStepGroup(0xc420422c60, 0xc42020c480, 0x1, 0x4, 0xc42018c9f0, 0x25, 0xc4208f4d90, 0xc42035105b, 0x6)
	/root/go/src/github.com/argoproj/argo/workflow/controller/operator.go:471 +0x79e
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeSteps(0xc420422c60, 0xc42018c0c0, 0x22, 0xc42043a750, 0x0, 0x0)
	/root/go/src/github.com/argoproj/argo/workflow/controller/operator.go:372 +0xcc4
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeTemplate(0xc420422c60, 0xc42026d520, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42018c0c0, ...)
	/root/go/src/github.com/argoproj/argo/workflow/controller/operator.go:254 +0x463
github.com/argoproj/argo/workflow/controller.(*WorkflowController).operateWorkflow(0xc4200b67e0, 0xc42044bb00)
	/root/go/src/github.com/argoproj/argo/workflow/controller/operator.go:94 +0x55f
github.com/argoproj/argo/workflow/controller.(*WorkflowController).Run(0xc4200b67e0, 0x187f640, 0xc4203fe100, 0xc4203b7cf0, 0xc420091ef0)
	/root/go/src/github.com/argoproj/argo/workflow/controller/controller.go:141 +0x61d
created by main.Run
	/root/go/src/github.com/argoproj/argo/cmd/workflow-controller/main.go:89 +0x345
```

I have a single workflow running which is provided below. I suspect the problem is that I was deliberately pointing the artifacts input path to a location that collided with a user specified volume. I was trying to load some github repositories into a persistent volume that could be passed around to other steps in my workflow.

After looking at the source, I realized this is probably a bad idea. It looks like artifacts inputs relies on mounting an emptyDir between the init container and actual pod. So getting that to work with my volume seemed like it would be sketchy. Since I already need to run a bash script I just added the relevant clone steps to my script.

However, it seems like a bug that a single bad workflow can cause the workflow controller to crash loop preventing other workflows from running.

Here's the YAML spec & status.

```
apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      kubernetes.io/created-by: |
        {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"kubeflow-test-infra","name":"argo-ui-9b4dc8568","uid":"444cec77-eb95-11e7-b323-42010af0024d","apiVersion":"extensions","resourceVersion":"57086"}}
    creationTimestamp: 2017-12-28T06:06:38Z
    generateName: argo-ui-9b4dc8568-
    labels:
      app: argo-ui
      pod-template-hash: "560874124"
    name: argo-ui-9b4dc8568-jvn8j
    namespace: kubeflow-test-infra
    ownerReferences:
    - apiVersion: extensions/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: argo-ui-9b4dc8568
      uid: 444cec77-eb95-11e7-b323-42010af0024d
    resourceVersion: "57096"
    selfLink: /api/v1/namespaces/kubeflow-test-infra/pods/argo-ui-9b4dc8568-jvn8j
    uid: 444ea468-eb95-11e7-b323-42010af0024d
  spec:
    containers:
    - env:
      - name: ARGO_NAMESPACE
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.namespace
      - name: IN_CLUSTER
        value: "true"
      image: argoproj/argoui:v2.0.0-alpha2
      imagePullPolicy: IfNotPresent
      name: argo-ui
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: argo-token-qjwjv
        readOnly: true
    dnsPolicy: ClusterFirst
    nodeName: gke-kubeflow-testing-default-pool-3cd81eea-tv6t
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: argo
    serviceAccountName: argo
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.alpha.kubernetes.io/notReady
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.alpha.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: argo-token-qjwjv
      secret:
        defaultMode: 420
        secretName: argo-token-qjwjv
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: 2017-12-28T06:06:38Z
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: 2017-12-28T06:06:39Z
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: 2017-12-28T06:06:38Z
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://c97a526389ca6927d0817cb57ac797648c96fa33145b54484d271ba287040e3b
      image: argoproj/argoui:v2.0.0-alpha2
      imageID: docker-pullable://argoproj/argoui@sha256:e00e638ac14ffd9c512ff9d16ba079edc0a76e65e3aeaeadd899170a90aa32bc
      lastState: {}
      name: argo-ui
      ready: true
      restartCount: 0
      state:
        running:
          startedAt: 2017-12-28T06:06:39Z
    hostIP: 10.142.0.4
    phase: Running
    podIP: 10.36.1.16
    qosClass: BestEffort
    startTime: 2017-12-28T06:06:38Z
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      kubernetes.io/created-by: |
        {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"kubeflow-test-infra","name":"workflow-controller-9654b5fbf","uid":"442cd8d6-eb95-11e7-b323-42010af0024d","apiVersion":"extensions","resourceVersion":"143043"}}
    creationTimestamp: 2017-12-28T23:48:20Z
    generateName: workflow-controller-9654b5fbf-
    labels:
      app: workflow-controller
      pod-template-hash: "521061969"
    name: workflow-controller-9654b5fbf-68hnf
    namespace: kubeflow-test-infra
    ownerReferences:
    - apiVersion: extensions/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: workflow-controller-9654b5fbf
      uid: 442cd8d6-eb95-11e7-b323-42010af0024d
    resourceVersion: "145439"
    selfLink: /api/v1/namespaces/kubeflow-test-infra/pods/workflow-controller-9654b5fbf-68hnf
    uid: 9559bade-ec29-11e7-b323-42010af0024d
  spec:
    containers:
    - args:
      - --configmap
      - workflow-controller-configmap
      command:
      - workflow-controller
      env:
      - name: ARGO_NAMESPACE
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.namespace
      image: argoproj/workflow-controller:v2.0.0-alpha2
      imagePullPolicy: IfNotPresent
      name: workflow-controller
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: argo-token-qjwjv
        readOnly: true
    dnsPolicy: ClusterFirst
    nodeName: gke-kubeflow-testing-default-pool-3cd81eea-tv6t
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: argo
    serviceAccountName: argo
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.alpha.kubernetes.io/notReady
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.alpha.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: argo-token-qjwjv
      secret:
        defaultMode: 420
        secretName: argo-token-qjwjv
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: 2017-12-28T23:48:20Z
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: 2017-12-28T23:54:55Z
      message: 'containers with unready status: [workflow-controller]'
      reason: ContainersNotReady
      status: "False"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: 2017-12-28T23:48:20Z
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://f44477012406236e9b956c4134479b486ecf02c51b47c67ce37a7038e125be1d
      image: argoproj/workflow-controller:v2.0.0-alpha2
      imageID: docker-pullable://argoproj/workflow-controller@sha256:a7da3e77936e81e86d362b35b219f0ea704993508a7ca0b34f80188040f72d4e
      lastState:
        terminated:
          containerID: docker://f44477012406236e9b956c4134479b486ecf02c51b47c67ce37a7038e125be1d
          exitCode: 2
          finishedAt: 2017-12-29T00:15:27Z
          reason: Error
          startedAt: 2017-12-29T00:15:27Z
      name: workflow-controller
      ready: false
      restartCount: 10
      state:
        waiting:
          message: Back-off 5m0s restarting failed container=workflow-controller pod=workflow-controller-9654b5fbf-68hnf_kubeflow-test-infra(9559bade-ec29-11e7-b323-42010af0024d)
          reason: CrashLoopBackOff
    hostIP: 10.142.0.4
    phase: Running
    podIP: 10.36.1.24
    qosClass: BestEffort
    startTime: 2017-12-28T23:48:20Z
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by jessesuen** [comment]
> After looking at the source, I realized this is probably a bad idea. It looks like artifacts inputs relies on mounting an emptyDir between the init container and actual pod. 

You are correct in your assessment. The volume mounts should not collide with an artifact path for the reasons you stated. The recommended solution is to place it in a sub directory in the volume. When this happens, the emptydir is not used. This was also discovered by another user and something we will be preventing during spec validation as part of https://github.com/argoproj/argo/issues/620#issuecomment-353437981.

> However, it seems like a bug that a single bad workflow can cause the workflow controller to crash loop preventing other workflows from running.

Right, panics should be recovered and gracefully handled. I will use this issue to work on graceful handling of panics(). I will use issue #620 to add validation to prevent collisions between volume mounts and artifact load paths.

**Comment by jlewi** [comment]
Thanks
