### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by francis-ax** [argoproj/argo#692]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG Report

**What happened**:

build the argo cli command from latest repo and it failed with following error.
```
Francis-Macbook-Pro:argo francis$ ./dist/argo version
argo version v2.0.0-1ec231b

Francis-Macbook-Pro:argo francis$ make clean
rm -rf /Users/francis/go/src/github.com/argoproj/argo/dist
Francis-Macbook-Pro:argo francis$ make cli
go build -v -i -ldflags "-X github.com/argoproj/argo.Version=2.0.0 -X github.com/argoproj/argo.Revision=1ec231b69a1a7d985d1d587980c34588019b04aa -X github.com/argoproj/argo.Branch=master -X github.com/argoproj/argo.Tag= -X github.com/argoproj/argo.ImageNamespace= -X github.com/argoproj/argo.ImageTag=2.0.0" -o /Users/francis/go/src/github.com/argoproj/argo/dist/argo ./cmd/argo
github.com/argoproj/argo/cmd/argo
Francis-Macbook-Pro:argo francis$ ./dist/argo install --controller-image hphsu/workflow-controller:latest --executor-image hphsu/argoexec:latest
Installing into namespace 'kube-system'
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1a83c5a]

goroutine 1 [running]:
github.com/argoproj/argo/vendor/k8s.io/client-go/kubernetes.NewForConfig(0x0, 0x0, 0x23d27e0, 0xc4202775a0)
	/Users/francis/go/src/github.com/argoproj/argo/vendor/k8s.io/client-go/kubernetes/clientset.go:358 +0x3a
github.com/argoproj/argo/cmd/argo/commands.initKubeClient(0x1cf49b1)
	/Users/francis/go/src/github.com/argoproj/argo/cmd/argo/commands/common.go:66 +0x6c
github.com/argoproj/argo/cmd/argo/commands.Install(0x24370a0, 0x1ceacf3, 0x13, 0x1ce1d68, 0x7, 0x1ce480d, 0xb, 0xc420344820, 0x1d, 0x7fff5fbffba7, ...)
	/Users/francis/go/src/github.com/argoproj/argo/cmd/argo/commands/install.go:61 +0xbb
github.com/argoproj/argo/cmd/argo/commands.install(0x24370a0, 0xc420278980, 0x0, 0x4)
	/Users/francis/go/src/github.com/argoproj/argo/cmd/argo/commands/install.go:83 +0x5b
github.com/argoproj/argo/vendor/github.com/spf13/cobra.(*Command).execute(0x24370a0, 0xc420278900, 0x4, 0x4, 0x24370a0, 0xc420278900)
	/Users/francis/go/src/github.com/argoproj/argo/vendor/github.com/spf13/cobra/command.go:702 +0x2c6
github.com/argoproj/argo/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x2437920, 0x1ce480d, 0xc420091f70, 0x1006424)
	/Users/francis/go/src/github.com/argoproj/argo/vendor/github.com/spf13/cobra/command.go:783 +0x30e
github.com/argoproj/argo/vendor/github.com/spf13/cobra.(*Command).Execute(0x2437920, 0xc420091f60, 0x1acb596)
	/Users/francis/go/src/github.com/argoproj/argo/vendor/github.com/spf13/cobra/command.go:736 +0x2b
main.main()
	/Users/francis/go/src/github.com/argoproj/argo/cmd/argo/main.go:11 +0x31

```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
$ argo version
```
- Kubernetes version :
```
$ kubectl version -o yaml
```

**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get <workflowname>
```
- executor logs:
```
$ kubectl logs <failedpodname> -c init
$ kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
$ kubectl logs -n kube-system $(kubectl get pods -l app=workflow-controller -n kube-system -o name)
```

**Comment by jessesuen** [comment]
Commit 1ec231b corresponds to a commit back in Dec 7th. I don't think this is recent code.

**Comment by francis-ax** [comment]
got 2 repos in my local laptop and confused with the old local repo.
