### ISSUE TITLE
Steps templates cannot generate OpenAPI models

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo#706]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

**What happened**:
I'm attempting to generate the OpenAPI/swagger definitions for the argo workflow spec using https://github.com/kubernetes/kube-openapi. During generation, the following error is encountered:
```
$ ./hack/update-openapigen.sh
ERROR: logging before flag.Parse: E0127 19:18:13.312749    7087 openapi.go:338] Error when generating: steps, Steps [][]github.com/argoproj/argo/pkg/apis/workflow/v1alpha1.WorkflowStep
ERROR: logging before flag.Parse: F0127 19:18:13.312777    7087 main.go:44] Error: Failed executing generator: some packages had errors:
slice Element kind Slice is not supported in [][]github.com/argoproj/argo/pkg/apis/workflow/v1alpha1.WorkflowStep
goroutine 1 [running]:
github.com/argoproj/argo/vendor/github.com/golang/glog.stacks(0xc42000e000, 0xc428510780, 0xd9, 0xe9)
        /Users/jsuen/go/src/github.com/argoproj/argo/vendor/github.com/golang/glog/glog.go:769 +0xcf
github.com/argoproj/argo/vendor/github.com/golang/glog.(*loggingT).output(0x181a7a0, 0xc400000003, 0xc428559ad0, 0x17c330c, 0x7, 0x2c, 0x0)
        /Users/jsuen/go/src/github.com/argoproj/argo/vendor/github.com/golang/glog/glog.go:720 +0x345
github.com/argoproj/argo/vendor/github.com/golang/glog.(*loggingT).printf(0x181a7a0, 0x3, 0x15122ef, 0x9, 0xc427aadf40, 0x1, 0x1)
        /Users/jsuen/go/src/github.com/argoproj/argo/vendor/github.com/golang/glog/glog.go:655 +0x14c
github.com/argoproj/argo/vendor/github.com/golang/glog.Fatalf(0x15122ef, 0x9, 0xc427aadf40, 0x1, 0x1)
        /Users/jsuen/go/src/github.com/argoproj/argo/vendor/github.com/golang/glog/glog.go:1148 +0x67
main.main()
        /Users/jsuen/go/src/github.com/argoproj/argo/vendor/k8s.io/kube-openapi/example/openapi-gen/main.go:44 +0x27f
exit status 255
```

It turns out nested containers is explicitly *not* supported by the OpenAPI spec. See the following issues:
https://github.com/OAI/OpenAPI-Specification/issues/40
https://github.com/OAI/OpenAPI-Specification/issues/53
https://github.com/swagger-api/swagger-core/issues/444

I think we will need to modify our steps template to become compliant with OpenAPI since there is a lot to lose by not being able to take advantage of the existing tooling. This of course will require us bumping the API version from v1alpha1 to something higher.

**Environment**:
- Argo version: 2.0.0-beta1

**Comment by jessesuen** [comment]
It appears nested lists is now supported: https://github.com/OAI/OpenAPI-Specification/issues/273

But I suspect the kube-openapi code generators may not support it yet.

**Comment by jessesuen** [comment]
Submitted PR https://github.com/kubernetes/kube-openapi/pull/34 to get kube-openapi to support nested lists.

**Comment by jessesuen** [comment]
Fixed in kubernetes/kube-openapi
