### ISSUE TITLE
Minion Manager fails when LaunchConfiguration doesn't have explicit AssociatePublicIpAddress

### ISSUE THREAD

**Issue by anapsix** [argoproj/argo#878]
### What did you do? (how to reproduce)
Started Minions Manager as described in [Use Spot Instances with your Kubernetes Clusters on AWS](https://blog.argoproj.io/use-spot-instances-with-your-kubernetes-clusters-on-aws-2a27f1887bb0) article.
Monitored minion-manager pod logs , noticed following error:
`Failed while checking instances in ASG: AssociatePublicIpAddress`

### What did you see? (include logs and screenshots as appropriate)
```
2018-06-07T13:49:16 INFO minion_manager MainThread: Starting ...
2018-06-07T13:49:16 INFO minion_manager MainThread: Using config from env: us-east-2
2018-06-07T13:49:16 INFO minion_manager MainThread: Using config from env: ['nodes.dev']
2018-06-07T13:49:16 INFO minion_manager MainThread: Starting minion-manager for scaling groups: ['nodes.dev'], in region us-east-2 for cloud provider aws
2018-06-07T13:49:16 INFO aws.minion-manager MainThread: Running AWS Minion Manager
2018-06-07T13:49:19 INFO aws.minion-manager MainThread: Added nodes.dev
2018-06-07T13:49:19 INFO aws.minion-manager MainThread: ASG nodes.dev using launch-config nodes.dev-20171024145757149700000004 with bid-info {'type': 'on-demand'}
2018-06-07T13:49:19 INFO aws.minion-manager.bid-advisor MainThread: Starting the BidAdvisor
2018-06-07T13:49:19 INFO aws.minion-manager.bid-advisor MainThread: Waiting for initial pricing information...
2018-06-07T13:49:19 INFO aws.minion-manager.bid-advisor Thread-2: Spot instance pricing info updated
2018-06-07T13:49:45 INFO aws.minion-manager.bid-advisor Thread-1: On-demand pricing info updated
2018-06-07T13:50:19 INFO aws.minion-manager.bid-advisor MainThread: Waiting for initial pricing information...
2018-06-07T13:51:19 INFO aws.minion-manager.price-reporter MainThread: PriceReporter thread started!
2018-06-07T13:51:19 INFO aws.minion-manager.price-reporter PriceReporter: Instance info not populated for nodes.dev!
2018-06-07T13:51:19 INFO aws.minion-manager.price-reporter MainThread: PriceReporterAPI thread started!
2018-06-07T13:51:19 INFO aws.minion-manager.minion-monitor PriceReporterAPI: Running Kubernetes client liveness checks ...
2018-06-07T13:51:19 INFO werkzeug PriceReporterAPI:  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-06-07T13:51:19 INFO aws.minion-manager MainThread: Processing ASG: nodes.dev
2018-06-07T13:51:19 INFO werkzeug MinionManagerRestAPI:  * Running on http://0.0.0.0:6000/ (Press CTRL+C to quit)
2018-06-07T13:51:21 INFO aws.minion-manager MainThread: Scheduling thread for i-07bf0bfe37051c788 after 678.894423999 seconds
2018-06-07T13:51:21 INFO aws.minion-manager MainThread: Added instance i-07bf0bfe37051c788 to kill threads
2018-06-07T13:51:21 INFO aws.minion-manager MainThread: Scheduling thread for i-0f1f1ed20f9c7a19a after 3246.104944 seconds
2018-06-07T13:51:21 INFO aws.minion-manager MainThread: Added instance i-0f1f1ed20f9c7a19a to kill threads
2018-06-07T13:51:21 INFO aws.minion-manager MainThread: Scheduling thread for i-0f7454e0ec90123fa after 102.104483999 seconds
2018-06-07T13:51:21 INFO aws.minion-manager MainThread: Added instance i-0f7454e0ec90123fa to kill threads
2018-06-07T13:51:21 INFO aws.minion-manager MainThread: ASG nodes.dev needs to be updated
2018-06-07T13:51:21 INFO aws.minion-manager.bid-advisor MainThread: Using spot_instance price 0.027800, on-demand price 0.092800 for instance type: t2.large, zone: us-east-2a
2018-06-07T13:51:21 INFO aws.minion-manager MainThread: Got new bid info from BidAdvisor: {'price': '0.0928', 'type': 'spot'}
2018-06-07T13:51:21 INFO aws.minion-manager MainThread: Updating ASG: nodes.dev, Bid: {'price': '0.0928', 'type': 'spot'}
2018-06-07T13:51:21 INFO aws.minion-manager MainThread: ASG( nodes.dev ): New bid price 0.0928
2018-06-07T13:51:21 INFO aws.minion-manager MainThread: ASG( nodes.dev ): New launch-config name: nodes.dev-20171024145757149700000004-0
2018-06-07T13:51:27 ERROR aws.minion-manager MainThread: Failed while checking instances in ASG: AssociatePublicIpAddress
Traceback (most recent call last):
  File "/ax/python/ax/platform/minion_manager/cloud_provider/aws/aws_minion_manager.py", line 446, in minion_manager_work
    self.update_scaling_group(asg_meta, new_bid_info)
  File "/ax/python/ax/platform/minion_manager/cloud_provider/aws/aws_minion_manager.py", line 287, in update_scaling_group
    self.create_lc_with_spot(new_lc_name, launch_config, spot_price)
  File "/usr/lib/python2.7/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/lib/python2.7/site-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/lib/python2.7/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/lib/python2.7/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/ax/python/ax/platform/minion_manager/cloud_provider/aws/aws_minion_manager.py", line 211, in create_lc_with_spot
    AssociatePublicIpAddress=launch_config.
  File "/usr/lib/python2.7/site-packages/bunch/__init__.py", line 128, in __getattr__
    raise AttributeError(k)
AttributeError: AssociatePublicIpAddress
```
### What did you expect?
Expected no errors.

### Additional details
Minion Manager is expecting explicitly defined `AssociatePublicIpAddress` within Launch Configuration definition [here](https://github.com/argoproj/argo/blob/7a896427ad2b312b41b4fb4e6daa48d860f0aecd/platform/source/lib/ax/platform/minion_manager/cloud_provider/aws/aws_minion_manager.py#L211-L212) and [here](https://github.com/argoproj/argo/blob/7a896427ad2b312b41b4fb4e6daa48d860f0aecd/platform/source/lib/ax/platform/minion_manager/cloud_provider/aws/aws_minion_manager.py#L243-L244)

Should default to false? Or should it lookup VPC settings?
```
AssociatePublicIpAddress=launch_config.AssociatePublicIpAddress or false
```

```
## my existing LC not explicitly defined
$ aws autoscaling describe-launch-configurations --launch-configuration-names nodes.dev-20171024145757149700000004 | grep "EbsOptimized" -A1
            "EbsOptimized": false
        }

## explicitly defined
$ aws autoscaling describe-launch-configurations --launch-configuration-names test | grep "EbsOptimized" -A1
            "EbsOptimized": false,
            "AssociatePublicIpAddress": false
```

**Comment by shrinandj** [comment]
We could set the default to False, but I'm confused by the existing `launch_config` object does not have the `AssociatePublicIpAddress` field in it. Instead of grepping for `EbsOptimized` with `-A1`, can you explicitly grep for `AssociatePublicIpAddress`?

I have an aws account with 11 launch-configurations. And all of them explicitly have the `AssociatePublicIpAddress` field in them.

```
$ aws --region us-west-2 autoscaling describe-launch-configurations | grep LaunchConfigurationName | wc -l
      11
$ aws --region us-west-2 autoscaling describe-launch-configurations | grep AssociatePublicIpAddress
            "AssociatePublicIpAddress": true
            "AssociatePublicIpAddress": true
            "AssociatePublicIpAddress": false
            "AssociatePublicIpAddress": false
            "AssociatePublicIpAddress": false
            "AssociatePublicIpAddress": false
            "AssociatePublicIpAddress": false
            "AssociatePublicIpAddress": false
            "AssociatePublicIpAddress": false
            "AssociatePublicIpAddress": false
            "AssociatePublicIpAddress": false
$ aws --region us-west-2 autoscaling describe-launch-configurations | grep AssociatePublicIpAddress | wc -l
      11
```

**Comment by anapsix** [comment]
I just wanted to show you a case where it wasn't there.. and if it's not there, prepping for it would provide no output :P
My LCs we're created by "kops".. in any case, it's possible to create LC without explicitly defining allocation of public IP, defaulting to VPC setting, afaik.

**Comment by anapsix** [comment]
I wonder if it's AWS bug..
I've upgraded my K8s cluster with KOPS today.. And noticed that for both previous and latest Launch Configurations KOPS created, it selected "VPC default", as I've mentioned.. 
![kops_lc](https://user-images.githubusercontent.com/1256199/41353818-fe6a5f54-6f25-11e8-97ba-389a4aef83e3.png)
However, after running `kops upgrade && kops rolling-update`, and checking latest Launch Configuration, I see the parameter `AssociatePublicIpAddress`:
```
aws autoscaling describe-launch-configurations --launch-configuration-names nodes.dev-20180613130215 | grep "EbsOptimized\|AssociatePublicIpAddress" -A1
            "EbsOptimized": false,
            "AssociatePublicIpAddress": false
        } 
```
Problem solved, beware!
