### ISSUE TITLE
Failed downloading artifact in argo-ui when artifact is stored in GCS.

### ISSUE THREAD

**Issue by soundTricker** [argoproj/argo#905]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

**What happened**:
In Argo-UI, Argo-UI show an error below when I click  download icon of an artifact what is stored in GCS.
```
{
code: "INTERNAL_ERROR",
message: "Unable to download artifact"
}
```

**What you expected to happen**:
Download the artifact.

**How to reproduce it (as minimally and precisely as possible)**:
1. Store an artifact to GCS
2. Show the workflow UI and show Artifact tab.
3. Click download icon 

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
$ argo version
argo: v2.1.1
  BuildDate: 2018-05-29T20:38:37Z
  GitCommit: ac241c95c13f08e868cd6f5ee32c9ce273e239ff
  GitTreeState: clean
  GitTag: v2.1.1
  GoVersion: go1.9.3
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: 2018-04-19T00:05:56Z
  compiler: gc
  gitCommit: dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92
  gitTreeState: clean
  gitVersion: v1.9.7
  goVersion: go1.9.3
  major: "1"
  minor: "9"
  platform: darwin/amd64
serverVersion:
  buildDate: 2018-06-15T21:48:39Z
  compiler: gc
  gitCommit: eb2e43842aaa21d6f0bb65d6adf5a84bbdc62eaf
  gitTreeState: clean
  gitVersion: v1.10.4-gke.2
  goVersion: go1.9.3b4
  major: "1"
  minor: 10+
  platform: linux/amd64

```

**Other debugging information (if applicable)**:
- API Log
```
{ NetworkingError: The header content contains invalid characters
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:358:11)
    at new ClientRequest (_http_client.js:86:14)
    at Object.exports.request (http.js:31:10)
    at handleRequest (/app/node_modules/aws-sdk/lib/http/node.js:42:23)
    at executeSend (/app/node_modules/aws-sdk/lib/event_listeners.js:304:29)
    at Request.SEND (/app/node_modules/aws-sdk/lib/event_listeners.js:318:9)
    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:101:18)
    at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/app/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)
  message: 'The header content contains invalid characters',
  code: 'NetworkingError',
  region: 'us-east-1',
  hostname: 'storage.googleapis.com',
  retryable: true,
  time: 2018-07-12T16:22:25.304Z }

```

**Comment by alexmt** [comment]
Fixed
